package com.microsoft.bingads.v13.api.test.entities;

import static org.junit.Assert.assertEquals;

import java.io.StringReader;
import java.io.StringWriter;

import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.JAXBException;

import org.junit.Test;

import com.microsoft.bingads.v13.campaignmanagement.CampaignFrequencyCapSetting;
import com.microsoft.bingads.v13.campaignmanagement.ChannelPlacementCriterion;
import com.microsoft.bingads.v13.campaignmanagement.FrequencyCapTimeGranularity;
import com.microsoft.bingads.v13.campaignmanagement.ImpressionTrackingSetting;
import com.microsoft.bingads.v13.campaignmanagement.ObjectFactory;
import com.microsoft.bingads.v13.campaignmanagement.ReachOptimizationGoal;
import com.microsoft.bingads.v13.campaignmanagement.ReachOptimizationGoalSetting;
import com.microsoft.bingads.v13.campaignmanagement.UnifiedAutomationSetting;

public class CampaignManagementProxyParityTest {
    private final ObjectFactory factory = new ObjectFactory();

    @Test
    public void settingsRoundTripThroughBaseSetting() throws JAXBException {
        ImpressionTrackingSetting impression = factory.createImpressionTrackingSetting();
        impression.setImpressionTrackingUrl("https://example.com/track");
        assertEquals("ImpressionTrackingSetting", impression.getType());
        assertEquals(impression.getImpressionTrackingUrl(),
                ((ImpressionTrackingSetting) roundTrip(factory.createSetting(impression),
                        ImpressionTrackingSetting.class)).getImpressionTrackingUrl());

        ReachOptimizationGoalSetting reach = factory.createReachOptimizationGoalSetting();
        reach.setOptimizationGoal(ReachOptimizationGoal.MAX_UNIQUE_REACH);
        assertEquals("ReachOptimizationGoalSetting", reach.getType());
        assertEquals(reach.getOptimizationGoal(),
                ((ReachOptimizationGoalSetting) roundTrip(factory.createSetting(reach),
                        ReachOptimizationGoalSetting.class)).getOptimizationGoal());
        assertEquals("MaxUniqueReach", ReachOptimizationGoal.MAX_UNIQUE_REACH.value());
        assertEquals(ReachOptimizationGoal.MAX_IMPRESSIONS,
                ReachOptimizationGoal.fromValue("MaxImpressions"));

        CampaignFrequencyCapSetting frequency = factory.createCampaignFrequencyCapSetting();
        frequency.setCapValue(5);
        frequency.setTimeGranularity(FrequencyCapTimeGranularity.DAY);
        assertEquals("CampaignFrequencyCapSetting", frequency.getType());
        CampaignFrequencyCapSetting restoredFrequency = (CampaignFrequencyCapSetting) roundTrip(
                factory.createSetting(frequency), CampaignFrequencyCapSetting.class);
        assertEquals(frequency.getCapValue(), restoredFrequency.getCapValue());
        assertEquals(frequency.getTimeGranularity(), restoredFrequency.getTimeGranularity());

        UnifiedAutomationSetting automation = factory.createUnifiedAutomationSetting();
        automation.setAutoGeneratedTextOptOut(true);
        automation.setFinalUrlExpansionOptOut(false);
        assertEquals("UnifiedAutomationSetting", automation.getType());
        UnifiedAutomationSetting restoredAutomation = (UnifiedAutomationSetting) roundTrip(
                factory.createSetting(automation), UnifiedAutomationSetting.class);
        assertEquals(automation.getAutoGeneratedTextOptOut(), restoredAutomation.getAutoGeneratedTextOptOut());
        assertEquals(automation.getFinalUrlExpansionOptOut(), restoredAutomation.getFinalUrlExpansionOptOut());
    }

    @Test
    public void channelPlacementRoundTripsThroughBaseCriterion() throws JAXBException {
        ChannelPlacementCriterion placement = factory.createChannelPlacementCriterion();
        placement.setChannelId(10);
        placement.setChannelPlacementId(42L);
        placement.setSubChannelName("Subchannel");
        assertEquals("ChannelPlacementCriterion", placement.getType());
        ChannelPlacementCriterion restored = (ChannelPlacementCriterion) roundTrip(
                factory.createCriterion(placement), ChannelPlacementCriterion.class);
        assertEquals(placement.getChannelId(), restored.getChannelId());
        assertEquals(placement.getChannelPlacementId(), restored.getChannelPlacementId());
        assertEquals(placement.getSubChannelName(), restored.getSubChannelName());
    }

    @Test
    public void newTypesHaveDirectCampaignManagementElements() throws JAXBException {
        assertElement(factory.createImpressionTrackingSetting(factory.createImpressionTrackingSetting()),
                ImpressionTrackingSetting.class);
        assertElement(factory.createReachOptimizationGoalSetting(factory.createReachOptimizationGoalSetting()),
                ReachOptimizationGoalSetting.class);
        assertElement(factory.createReachOptimizationGoal(ReachOptimizationGoal.MAX_IMPRESSIONS),
                ReachOptimizationGoal.class);
        assertElement(factory.createCampaignFrequencyCapSetting(factory.createCampaignFrequencyCapSetting()),
                CampaignFrequencyCapSetting.class);
        assertElement(factory.createUnifiedAutomationSetting(factory.createUnifiedAutomationSetting()),
                UnifiedAutomationSetting.class);
        assertElement(factory.createChannelPlacementCriterion(factory.createChannelPlacementCriterion()),
                ChannelPlacementCriterion.class);
    }

    private void assertElement(JAXBElement<?> element, Class<?> expectedType) throws JAXBException {
        assertEquals("https://bingads.microsoft.com/CampaignManagement/v13", element.getName().getNamespaceURI());
        assertEquals(expectedType.getSimpleName(), element.getName().getLocalPart());
        assertEquals(expectedType, roundTrip(element, expectedType).getClass());
    }

    private Object roundTrip(JAXBElement<?> element, Class<?> expectedType) throws JAXBException {
        JAXBContext context = JAXBContext.newInstance(ObjectFactory.class);
        StringWriter xml = new StringWriter();
        context.createMarshaller().marshal(element, xml);
        JAXBElement<?> restored = (JAXBElement<?>) context.createUnmarshaller()
                .unmarshal(new StringReader(xml.toString()));
        assertEquals(expectedType, restored.getValue().getClass());
        return restored.getValue();
    }
}
