
package com.microsoft.bingads.optimizer;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IOptimizerService", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IOptimizerService {


    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.optimizer.GetBudgetOpportunitiesResponse>
     */
    @WebMethod(operationName = "GetBudgetOpportunities", action = "GetBudgetOpportunities")
    public Response<GetBudgetOpportunitiesResponse> getBudgetOpportunitiesAsync(
        @WebParam(name = "GetBudgetOpportunitiesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetBudgetOpportunitiesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetBudgetOpportunities", action = "GetBudgetOpportunities")
    public Future<?> getBudgetOpportunitiesAsync(
        @WebParam(name = "GetBudgetOpportunitiesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetBudgetOpportunitiesRequest parameters,
        @WebParam(name = "GetBudgetOpportunitiesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetBudgetOpportunitiesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.optimizer.GetBudgetOpportunitiesResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetBudgetOpportunities", action = "GetBudgetOpportunities")
    @WebResult(name = "GetBudgetOpportunitiesResponse", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
    public GetBudgetOpportunitiesResponse getBudgetOpportunities(
        @WebParam(name = "GetBudgetOpportunitiesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetBudgetOpportunitiesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.optimizer.GetBudgetLandscapeResponse>
     */
    @WebMethod(operationName = "GetBudgetLandscape", action = "GetBudgetLandscape")
    public Response<GetBudgetLandscapeResponse> getBudgetLandscapeAsync(
        @WebParam(name = "GetBudgetLandscapeRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetBudgetLandscapeRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetBudgetLandscape", action = "GetBudgetLandscape")
    public Future<?> getBudgetLandscapeAsync(
        @WebParam(name = "GetBudgetLandscapeRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetBudgetLandscapeRequest parameters,
        @WebParam(name = "GetBudgetLandscapeResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetBudgetLandscapeResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.optimizer.GetBudgetLandscapeResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetBudgetLandscape", action = "GetBudgetLandscape")
    @WebResult(name = "GetBudgetLandscapeResponse", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
    public GetBudgetLandscapeResponse getBudgetLandscape(
        @WebParam(name = "GetBudgetLandscapeRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetBudgetLandscapeRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.optimizer.GetBidOpportunitiesResponse>
     */
    @WebMethod(operationName = "GetBidOpportunities", action = "GetBidOpportunities")
    public Response<GetBidOpportunitiesResponse> getBidOpportunitiesAsync(
        @WebParam(name = "GetBidOpportunitiesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetBidOpportunitiesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetBidOpportunities", action = "GetBidOpportunities")
    public Future<?> getBidOpportunitiesAsync(
        @WebParam(name = "GetBidOpportunitiesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetBidOpportunitiesRequest parameters,
        @WebParam(name = "GetBidOpportunitiesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetBidOpportunitiesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.optimizer.GetBidOpportunitiesResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetBidOpportunities", action = "GetBidOpportunities")
    @WebResult(name = "GetBidOpportunitiesResponse", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
    public GetBidOpportunitiesResponse getBidOpportunities(
        @WebParam(name = "GetBidOpportunitiesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetBidOpportunitiesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.optimizer.GetKeywordOpportunitiesResponse>
     */
    @WebMethod(operationName = "GetKeywordOpportunities", action = "GetKeywordOpportunities")
    public Response<GetKeywordOpportunitiesResponse> getKeywordOpportunitiesAsync(
        @WebParam(name = "GetKeywordOpportunitiesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetKeywordOpportunitiesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetKeywordOpportunities", action = "GetKeywordOpportunities")
    public Future<?> getKeywordOpportunitiesAsync(
        @WebParam(name = "GetKeywordOpportunitiesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetKeywordOpportunitiesRequest parameters,
        @WebParam(name = "GetKeywordOpportunitiesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetKeywordOpportunitiesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.optimizer.GetKeywordOpportunitiesResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetKeywordOpportunities", action = "GetKeywordOpportunities")
    @WebResult(name = "GetKeywordOpportunitiesResponse", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
    public GetKeywordOpportunitiesResponse getKeywordOpportunities(
        @WebParam(name = "GetKeywordOpportunitiesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetKeywordOpportunitiesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.optimizer.GetBroadMatchOpportunitiesResponse>
     */
    @WebMethod(operationName = "GetBroadMatchOpportunities", action = "GetBroadMatchOpportunities")
    public Response<GetBroadMatchOpportunitiesResponse> getBroadMatchOpportunitiesAsync(
        @WebParam(name = "GetBroadMatchOpportunitiesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetBroadMatchOpportunitiesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetBroadMatchOpportunities", action = "GetBroadMatchOpportunities")
    public Future<?> getBroadMatchOpportunitiesAsync(
        @WebParam(name = "GetBroadMatchOpportunitiesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetBroadMatchOpportunitiesRequest parameters,
        @WebParam(name = "GetBroadMatchOpportunitiesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetBroadMatchOpportunitiesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.optimizer.GetBroadMatchOpportunitiesResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetBroadMatchOpportunities", action = "GetBroadMatchOpportunities")
    @WebResult(name = "GetBroadMatchOpportunitiesResponse", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
    public GetBroadMatchOpportunitiesResponse getBroadMatchOpportunities(
        @WebParam(name = "GetBroadMatchOpportunitiesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetBroadMatchOpportunitiesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.optimizer.GetBroadMatchSearchQueriesResponse>
     */
    @WebMethod(operationName = "GetBroadMatchSearchQueries", action = "GetBroadMatchSearchQueries")
    public Response<GetBroadMatchSearchQueriesResponse> getBroadMatchSearchQueriesAsync(
        @WebParam(name = "GetBroadMatchSearchQueriesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetBroadMatchSearchQueriesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetBroadMatchSearchQueries", action = "GetBroadMatchSearchQueries")
    public Future<?> getBroadMatchSearchQueriesAsync(
        @WebParam(name = "GetBroadMatchSearchQueriesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetBroadMatchSearchQueriesRequest parameters,
        @WebParam(name = "GetBroadMatchSearchQueriesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetBroadMatchSearchQueriesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.optimizer.GetBroadMatchSearchQueriesResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetBroadMatchSearchQueries", action = "GetBroadMatchSearchQueries")
    @WebResult(name = "GetBroadMatchSearchQueriesResponse", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
    public GetBroadMatchSearchQueriesResponse getBroadMatchSearchQueries(
        @WebParam(name = "GetBroadMatchSearchQueriesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        GetBroadMatchSearchQueriesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.optimizer.ApplyOpportunityModifiersResponse>
     */
    @WebMethod(operationName = "ApplyOpportunityModifiers", action = "ApplyOpportunityModifiers")
    public Response<ApplyOpportunityModifiersResponse> applyOpportunityModifiersAsync(
        @WebParam(name = "ApplyOpportunityModifiersRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        ApplyOpportunityModifiersRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ApplyOpportunityModifiers", action = "ApplyOpportunityModifiers")
    public Future<?> applyOpportunityModifiersAsync(
        @WebParam(name = "ApplyOpportunityModifiersRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        ApplyOpportunityModifiersRequest parameters,
        @WebParam(name = "ApplyOpportunityModifiersResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ApplyOpportunityModifiersResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.optimizer.ApplyOpportunityModifiersResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFaultDetail_Exception
     */
    @WebMethod(operationName = "ApplyOpportunityModifiers", action = "ApplyOpportunityModifiers")
    @WebResult(name = "ApplyOpportunityModifiersResponse", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
    public ApplyOpportunityModifiersResponse applyOpportunityModifiers(
        @WebParam(name = "ApplyOpportunityModifiersRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        ApplyOpportunityModifiersRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.optimizer.ApplyOpportunitiesResponse>
     */
    @WebMethod(operationName = "ApplyOpportunities", action = "ApplyOpportunities")
    public Response<ApplyOpportunitiesResponse> applyOpportunitiesAsync(
        @WebParam(name = "ApplyOpportunitiesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        ApplyOpportunitiesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ApplyOpportunities", action = "ApplyOpportunities")
    public Future<?> applyOpportunitiesAsync(
        @WebParam(name = "ApplyOpportunitiesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        ApplyOpportunitiesRequest parameters,
        @WebParam(name = "ApplyOpportunitiesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ApplyOpportunitiesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.optimizer.ApplyOpportunitiesResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFaultDetail_Exception
     */
    @WebMethod(operationName = "ApplyOpportunities", action = "ApplyOpportunities")
    @WebResult(name = "ApplyOpportunitiesResponse", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
    public ApplyOpportunitiesResponse applyOpportunities(
        @WebParam(name = "ApplyOpportunitiesRequest", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", partName = "parameters")
        ApplyOpportunitiesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

}
