
package com.microsoft.bingads.optimizer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OptimizerService", targetNamespace = "https://bingads.microsoft.com/Optimizer/v9", wsdlLocation = "https://api.sandbox.bingads.microsoft.com/Api/Advertiser/Optimizer/v9/OptimizerService.svc?wsdl")
public class OptimizerService
    extends Service
{

    private final static URL OPTIMIZERSERVICE_WSDL_LOCATION;
    private final static WebServiceException OPTIMIZERSERVICE_EXCEPTION;
    private final static QName OPTIMIZERSERVICE_QNAME = new QName("https://bingads.microsoft.com/Optimizer/v9", "OptimizerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.sandbox.bingads.microsoft.com/Api/Advertiser/Optimizer/v9/OptimizerService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OPTIMIZERSERVICE_WSDL_LOCATION = url;
        OPTIMIZERSERVICE_EXCEPTION = e;
    }

    public OptimizerService() {
        super(__getWsdlLocation(), OPTIMIZERSERVICE_QNAME);
    }

    public OptimizerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns IOptimizerService
     */
    @WebEndpoint(name = "BasicHttpBinding_IOptimizerService")
    public IOptimizerService getBasicHttpBindingIOptimizerService() {
        return super.getPort(new QName("https://bingads.microsoft.com/Optimizer/v9", "BasicHttpBinding_IOptimizerService"), IOptimizerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IOptimizerService
     */
    @WebEndpoint(name = "BasicHttpBinding_IOptimizerService")
    public IOptimizerService getBasicHttpBindingIOptimizerService(WebServiceFeature... features) {
        return super.getPort(new QName("https://bingads.microsoft.com/Optimizer/v9", "BasicHttpBinding_IOptimizerService"), IOptimizerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPTIMIZERSERVICE_EXCEPTION!= null) {
            throw OPTIMIZERSERVICE_EXCEPTION;
        }
        return OPTIMIZERSERVICE_WSDL_LOCATION;
    }

}
