
package com.microsoft.bingads.v11.adinsight;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IAdInsightService", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAdInsightService {


    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetBidOpportunitiesResponse>
     */
    @WebMethod(operationName = "GetBidOpportunities", action = "GetBidOpportunities")
    public Response<GetBidOpportunitiesResponse> getBidOpportunitiesAsync(
        @WebParam(name = "GetBidOpportunitiesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetBidOpportunitiesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetBidOpportunities", action = "GetBidOpportunities")
    public Future<?> getBidOpportunitiesAsync(
        @WebParam(name = "GetBidOpportunitiesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetBidOpportunitiesRequest parameters,
        @WebParam(name = "GetBidOpportunitiesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetBidOpportunitiesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetBidOpportunitiesResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetBidOpportunities", action = "GetBidOpportunities")
    @WebResult(name = "GetBidOpportunitiesResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetBidOpportunitiesResponse getBidOpportunities(
        @WebParam(name = "GetBidOpportunitiesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetBidOpportunitiesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetBudgetOpportunitiesResponse>
     */
    @WebMethod(operationName = "GetBudgetOpportunities", action = "GetBudgetOpportunities")
    public Response<GetBudgetOpportunitiesResponse> getBudgetOpportunitiesAsync(
        @WebParam(name = "GetBudgetOpportunitiesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetBudgetOpportunitiesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetBudgetOpportunities", action = "GetBudgetOpportunities")
    public Future<?> getBudgetOpportunitiesAsync(
        @WebParam(name = "GetBudgetOpportunitiesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetBudgetOpportunitiesRequest parameters,
        @WebParam(name = "GetBudgetOpportunitiesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetBudgetOpportunitiesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetBudgetOpportunitiesResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetBudgetOpportunities", action = "GetBudgetOpportunities")
    @WebResult(name = "GetBudgetOpportunitiesResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetBudgetOpportunitiesResponse getBudgetOpportunities(
        @WebParam(name = "GetBudgetOpportunitiesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetBudgetOpportunitiesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetKeywordOpportunitiesResponse>
     */
    @WebMethod(operationName = "GetKeywordOpportunities", action = "GetKeywordOpportunities")
    public Response<GetKeywordOpportunitiesResponse> getKeywordOpportunitiesAsync(
        @WebParam(name = "GetKeywordOpportunitiesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordOpportunitiesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetKeywordOpportunities", action = "GetKeywordOpportunities")
    public Future<?> getKeywordOpportunitiesAsync(
        @WebParam(name = "GetKeywordOpportunitiesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordOpportunitiesRequest parameters,
        @WebParam(name = "GetKeywordOpportunitiesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetKeywordOpportunitiesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetKeywordOpportunitiesResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetKeywordOpportunities", action = "GetKeywordOpportunities")
    @WebResult(name = "GetKeywordOpportunitiesResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetKeywordOpportunitiesResponse getKeywordOpportunities(
        @WebParam(name = "GetKeywordOpportunitiesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordOpportunitiesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetEstimatedBidByKeywordIdsResponse>
     */
    @WebMethod(operationName = "GetEstimatedBidByKeywordIds", action = "GetEstimatedBidByKeywordIds")
    public Response<GetEstimatedBidByKeywordIdsResponse> getEstimatedBidByKeywordIdsAsync(
        @WebParam(name = "GetEstimatedBidByKeywordIdsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetEstimatedBidByKeywordIdsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetEstimatedBidByKeywordIds", action = "GetEstimatedBidByKeywordIds")
    public Future<?> getEstimatedBidByKeywordIdsAsync(
        @WebParam(name = "GetEstimatedBidByKeywordIdsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetEstimatedBidByKeywordIdsRequest parameters,
        @WebParam(name = "GetEstimatedBidByKeywordIdsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetEstimatedBidByKeywordIdsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetEstimatedBidByKeywordIdsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetEstimatedBidByKeywordIds", action = "GetEstimatedBidByKeywordIds")
    @WebResult(name = "GetEstimatedBidByKeywordIdsResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetEstimatedBidByKeywordIdsResponse getEstimatedBidByKeywordIds(
        @WebParam(name = "GetEstimatedBidByKeywordIdsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetEstimatedBidByKeywordIdsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetEstimatedPositionByKeywordIdsResponse>
     */
    @WebMethod(operationName = "GetEstimatedPositionByKeywordIds", action = "GetEstimatedPositionByKeywordIds")
    public Response<GetEstimatedPositionByKeywordIdsResponse> getEstimatedPositionByKeywordIdsAsync(
        @WebParam(name = "GetEstimatedPositionByKeywordIdsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetEstimatedPositionByKeywordIdsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetEstimatedPositionByKeywordIds", action = "GetEstimatedPositionByKeywordIds")
    public Future<?> getEstimatedPositionByKeywordIdsAsync(
        @WebParam(name = "GetEstimatedPositionByKeywordIdsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetEstimatedPositionByKeywordIdsRequest parameters,
        @WebParam(name = "GetEstimatedPositionByKeywordIdsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetEstimatedPositionByKeywordIdsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetEstimatedPositionByKeywordIdsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetEstimatedPositionByKeywordIds", action = "GetEstimatedPositionByKeywordIds")
    @WebResult(name = "GetEstimatedPositionByKeywordIdsResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetEstimatedPositionByKeywordIdsResponse getEstimatedPositionByKeywordIds(
        @WebParam(name = "GetEstimatedPositionByKeywordIdsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetEstimatedPositionByKeywordIdsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetEstimatedBidByKeywordsResponse>
     */
    @WebMethod(operationName = "GetEstimatedBidByKeywords", action = "GetEstimatedBidByKeywords")
    public Response<GetEstimatedBidByKeywordsResponse> getEstimatedBidByKeywordsAsync(
        @WebParam(name = "GetEstimatedBidByKeywordsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetEstimatedBidByKeywordsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetEstimatedBidByKeywords", action = "GetEstimatedBidByKeywords")
    public Future<?> getEstimatedBidByKeywordsAsync(
        @WebParam(name = "GetEstimatedBidByKeywordsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetEstimatedBidByKeywordsRequest parameters,
        @WebParam(name = "GetEstimatedBidByKeywordsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetEstimatedBidByKeywordsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetEstimatedBidByKeywordsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetEstimatedBidByKeywords", action = "GetEstimatedBidByKeywords")
    @WebResult(name = "GetEstimatedBidByKeywordsResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetEstimatedBidByKeywordsResponse getEstimatedBidByKeywords(
        @WebParam(name = "GetEstimatedBidByKeywordsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetEstimatedBidByKeywordsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetEstimatedPositionByKeywordsResponse>
     */
    @WebMethod(operationName = "GetEstimatedPositionByKeywords", action = "GetEstimatedPositionByKeywords")
    public Response<GetEstimatedPositionByKeywordsResponse> getEstimatedPositionByKeywordsAsync(
        @WebParam(name = "GetEstimatedPositionByKeywordsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetEstimatedPositionByKeywordsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetEstimatedPositionByKeywords", action = "GetEstimatedPositionByKeywords")
    public Future<?> getEstimatedPositionByKeywordsAsync(
        @WebParam(name = "GetEstimatedPositionByKeywordsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetEstimatedPositionByKeywordsRequest parameters,
        @WebParam(name = "GetEstimatedPositionByKeywordsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetEstimatedPositionByKeywordsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetEstimatedPositionByKeywordsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetEstimatedPositionByKeywords", action = "GetEstimatedPositionByKeywords")
    @WebResult(name = "GetEstimatedPositionByKeywordsResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetEstimatedPositionByKeywordsResponse getEstimatedPositionByKeywords(
        @WebParam(name = "GetEstimatedPositionByKeywordsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetEstimatedPositionByKeywordsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetBidLandscapeByAdGroupIdsResponse>
     */
    @WebMethod(operationName = "GetBidLandscapeByAdGroupIds", action = "GetBidLandscapeByAdGroupIds")
    public Response<GetBidLandscapeByAdGroupIdsResponse> getBidLandscapeByAdGroupIdsAsync(
        @WebParam(name = "GetBidLandscapeByAdGroupIdsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetBidLandscapeByAdGroupIdsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetBidLandscapeByAdGroupIds", action = "GetBidLandscapeByAdGroupIds")
    public Future<?> getBidLandscapeByAdGroupIdsAsync(
        @WebParam(name = "GetBidLandscapeByAdGroupIdsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetBidLandscapeByAdGroupIdsRequest parameters,
        @WebParam(name = "GetBidLandscapeByAdGroupIdsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetBidLandscapeByAdGroupIdsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetBidLandscapeByAdGroupIdsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetBidLandscapeByAdGroupIds", action = "GetBidLandscapeByAdGroupIds")
    @WebResult(name = "GetBidLandscapeByAdGroupIdsResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetBidLandscapeByAdGroupIdsResponse getBidLandscapeByAdGroupIds(
        @WebParam(name = "GetBidLandscapeByAdGroupIdsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetBidLandscapeByAdGroupIdsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetBidLandscapeByKeywordIdsResponse>
     */
    @WebMethod(operationName = "GetBidLandscapeByKeywordIds", action = "GetBidLandscapeByKeywordIds")
    public Response<GetBidLandscapeByKeywordIdsResponse> getBidLandscapeByKeywordIdsAsync(
        @WebParam(name = "GetBidLandscapeByKeywordIdsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetBidLandscapeByKeywordIdsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetBidLandscapeByKeywordIds", action = "GetBidLandscapeByKeywordIds")
    public Future<?> getBidLandscapeByKeywordIdsAsync(
        @WebParam(name = "GetBidLandscapeByKeywordIdsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetBidLandscapeByKeywordIdsRequest parameters,
        @WebParam(name = "GetBidLandscapeByKeywordIdsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetBidLandscapeByKeywordIdsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetBidLandscapeByKeywordIdsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetBidLandscapeByKeywordIds", action = "GetBidLandscapeByKeywordIds")
    @WebResult(name = "GetBidLandscapeByKeywordIdsResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetBidLandscapeByKeywordIdsResponse getBidLandscapeByKeywordIds(
        @WebParam(name = "GetBidLandscapeByKeywordIdsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetBidLandscapeByKeywordIdsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetHistoricalKeywordPerformanceResponse>
     */
    @WebMethod(operationName = "GetHistoricalKeywordPerformance", action = "GetHistoricalKeywordPerformance")
    public Response<GetHistoricalKeywordPerformanceResponse> getHistoricalKeywordPerformanceAsync(
        @WebParam(name = "GetHistoricalKeywordPerformanceRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetHistoricalKeywordPerformanceRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetHistoricalKeywordPerformance", action = "GetHistoricalKeywordPerformance")
    public Future<?> getHistoricalKeywordPerformanceAsync(
        @WebParam(name = "GetHistoricalKeywordPerformanceRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetHistoricalKeywordPerformanceRequest parameters,
        @WebParam(name = "GetHistoricalKeywordPerformanceResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetHistoricalKeywordPerformanceResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetHistoricalKeywordPerformanceResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetHistoricalKeywordPerformance", action = "GetHistoricalKeywordPerformance")
    @WebResult(name = "GetHistoricalKeywordPerformanceResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetHistoricalKeywordPerformanceResponse getHistoricalKeywordPerformance(
        @WebParam(name = "GetHistoricalKeywordPerformanceRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetHistoricalKeywordPerformanceRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetHistoricalSearchCountResponse>
     */
    @WebMethod(operationName = "GetHistoricalSearchCount", action = "GetHistoricalSearchCount")
    public Response<GetHistoricalSearchCountResponse> getHistoricalSearchCountAsync(
        @WebParam(name = "GetHistoricalSearchCountRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetHistoricalSearchCountRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetHistoricalSearchCount", action = "GetHistoricalSearchCount")
    public Future<?> getHistoricalSearchCountAsync(
        @WebParam(name = "GetHistoricalSearchCountRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetHistoricalSearchCountRequest parameters,
        @WebParam(name = "GetHistoricalSearchCountResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetHistoricalSearchCountResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetHistoricalSearchCountResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetHistoricalSearchCount", action = "GetHistoricalSearchCount")
    @WebResult(name = "GetHistoricalSearchCountResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetHistoricalSearchCountResponse getHistoricalSearchCount(
        @WebParam(name = "GetHistoricalSearchCountRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetHistoricalSearchCountRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetKeywordCategoriesResponse>
     */
    @WebMethod(operationName = "GetKeywordCategories", action = "GetKeywordCategories")
    public Response<GetKeywordCategoriesResponse> getKeywordCategoriesAsync(
        @WebParam(name = "GetKeywordCategoriesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordCategoriesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetKeywordCategories", action = "GetKeywordCategories")
    public Future<?> getKeywordCategoriesAsync(
        @WebParam(name = "GetKeywordCategoriesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordCategoriesRequest parameters,
        @WebParam(name = "GetKeywordCategoriesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetKeywordCategoriesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetKeywordCategoriesResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetKeywordCategories", action = "GetKeywordCategories")
    @WebResult(name = "GetKeywordCategoriesResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetKeywordCategoriesResponse getKeywordCategories(
        @WebParam(name = "GetKeywordCategoriesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordCategoriesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetKeywordDemographicsResponse>
     */
    @WebMethod(operationName = "GetKeywordDemographics", action = "GetKeywordDemographics")
    public Response<GetKeywordDemographicsResponse> getKeywordDemographicsAsync(
        @WebParam(name = "GetKeywordDemographicsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordDemographicsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetKeywordDemographics", action = "GetKeywordDemographics")
    public Future<?> getKeywordDemographicsAsync(
        @WebParam(name = "GetKeywordDemographicsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordDemographicsRequest parameters,
        @WebParam(name = "GetKeywordDemographicsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetKeywordDemographicsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetKeywordDemographicsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetKeywordDemographics", action = "GetKeywordDemographics")
    @WebResult(name = "GetKeywordDemographicsResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetKeywordDemographicsResponse getKeywordDemographics(
        @WebParam(name = "GetKeywordDemographicsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordDemographicsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetKeywordLocationsResponse>
     */
    @WebMethod(operationName = "GetKeywordLocations", action = "GetKeywordLocations")
    public Response<GetKeywordLocationsResponse> getKeywordLocationsAsync(
        @WebParam(name = "GetKeywordLocationsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordLocationsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetKeywordLocations", action = "GetKeywordLocations")
    public Future<?> getKeywordLocationsAsync(
        @WebParam(name = "GetKeywordLocationsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordLocationsRequest parameters,
        @WebParam(name = "GetKeywordLocationsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetKeywordLocationsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetKeywordLocationsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetKeywordLocations", action = "GetKeywordLocations")
    @WebResult(name = "GetKeywordLocationsResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetKeywordLocationsResponse getKeywordLocations(
        @WebParam(name = "GetKeywordLocationsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordLocationsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.SuggestKeywordsForUrlResponse>
     */
    @WebMethod(operationName = "SuggestKeywordsForUrl", action = "SuggestKeywordsForUrl")
    public Response<SuggestKeywordsForUrlResponse> suggestKeywordsForUrlAsync(
        @WebParam(name = "SuggestKeywordsForUrlRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        SuggestKeywordsForUrlRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SuggestKeywordsForUrl", action = "SuggestKeywordsForUrl")
    public Future<?> suggestKeywordsForUrlAsync(
        @WebParam(name = "SuggestKeywordsForUrlRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        SuggestKeywordsForUrlRequest parameters,
        @WebParam(name = "SuggestKeywordsForUrlResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SuggestKeywordsForUrlResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.SuggestKeywordsForUrlResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "SuggestKeywordsForUrl", action = "SuggestKeywordsForUrl")
    @WebResult(name = "SuggestKeywordsForUrlResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public SuggestKeywordsForUrlResponse suggestKeywordsForUrl(
        @WebParam(name = "SuggestKeywordsForUrlRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        SuggestKeywordsForUrlRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.SuggestKeywordsFromExistingKeywordsResponse>
     */
    @WebMethod(operationName = "SuggestKeywordsFromExistingKeywords", action = "SuggestKeywordsFromExistingKeywords")
    public Response<SuggestKeywordsFromExistingKeywordsResponse> suggestKeywordsFromExistingKeywordsAsync(
        @WebParam(name = "SuggestKeywordsFromExistingKeywordsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        SuggestKeywordsFromExistingKeywordsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SuggestKeywordsFromExistingKeywords", action = "SuggestKeywordsFromExistingKeywords")
    public Future<?> suggestKeywordsFromExistingKeywordsAsync(
        @WebParam(name = "SuggestKeywordsFromExistingKeywordsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        SuggestKeywordsFromExistingKeywordsRequest parameters,
        @WebParam(name = "SuggestKeywordsFromExistingKeywordsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SuggestKeywordsFromExistingKeywordsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.SuggestKeywordsFromExistingKeywordsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "SuggestKeywordsFromExistingKeywords", action = "SuggestKeywordsFromExistingKeywords")
    @WebResult(name = "SuggestKeywordsFromExistingKeywordsResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public SuggestKeywordsFromExistingKeywordsResponse suggestKeywordsFromExistingKeywords(
        @WebParam(name = "SuggestKeywordsFromExistingKeywordsRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        SuggestKeywordsFromExistingKeywordsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetAuctionInsightDataResponse>
     */
    @WebMethod(operationName = "GetAuctionInsightData", action = "GetAuctionInsightData")
    public Response<GetAuctionInsightDataResponse> getAuctionInsightDataAsync(
        @WebParam(name = "GetAuctionInsightDataRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetAuctionInsightDataRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAuctionInsightData", action = "GetAuctionInsightData")
    public Future<?> getAuctionInsightDataAsync(
        @WebParam(name = "GetAuctionInsightDataRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetAuctionInsightDataRequest parameters,
        @WebParam(name = "GetAuctionInsightDataResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAuctionInsightDataResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetAuctionInsightDataResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetAuctionInsightData", action = "GetAuctionInsightData")
    @WebResult(name = "GetAuctionInsightDataResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetAuctionInsightDataResponse getAuctionInsightData(
        @WebParam(name = "GetAuctionInsightDataRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetAuctionInsightDataRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetDomainCategoriesResponse>
     */
    @WebMethod(operationName = "GetDomainCategories", action = "GetDomainCategories")
    public Response<GetDomainCategoriesResponse> getDomainCategoriesAsync(
        @WebParam(name = "GetDomainCategoriesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetDomainCategoriesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetDomainCategories", action = "GetDomainCategories")
    public Future<?> getDomainCategoriesAsync(
        @WebParam(name = "GetDomainCategoriesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetDomainCategoriesRequest parameters,
        @WebParam(name = "GetDomainCategoriesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetDomainCategoriesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetDomainCategoriesResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetDomainCategories", action = "GetDomainCategories")
    @WebResult(name = "GetDomainCategoriesResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetDomainCategoriesResponse getDomainCategories(
        @WebParam(name = "GetDomainCategoriesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetDomainCategoriesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.PutMetricDataResponse>
     */
    @WebMethod(operationName = "PutMetricData", action = "PutMetricData")
    public Response<PutMetricDataResponse> putMetricDataAsync(
        @WebParam(name = "PutMetricDataRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        PutMetricDataRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "PutMetricData", action = "PutMetricData")
    public Future<?> putMetricDataAsync(
        @WebParam(name = "PutMetricDataRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        PutMetricDataRequest parameters,
        @WebParam(name = "PutMetricDataResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<PutMetricDataResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.PutMetricDataResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "PutMetricData", action = "PutMetricData")
    @WebResult(name = "PutMetricDataResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public PutMetricDataResponse putMetricData(
        @WebParam(name = "PutMetricDataRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        PutMetricDataRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetKeywordIdeaCategoriesResponse>
     */
    @WebMethod(operationName = "GetKeywordIdeaCategories", action = "GetKeywordIdeaCategories")
    public Response<GetKeywordIdeaCategoriesResponse> getKeywordIdeaCategoriesAsync(
        @WebParam(name = "GetKeywordIdeaCategoriesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordIdeaCategoriesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetKeywordIdeaCategories", action = "GetKeywordIdeaCategories")
    public Future<?> getKeywordIdeaCategoriesAsync(
        @WebParam(name = "GetKeywordIdeaCategoriesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordIdeaCategoriesRequest parameters,
        @WebParam(name = "GetKeywordIdeaCategoriesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetKeywordIdeaCategoriesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetKeywordIdeaCategoriesResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetKeywordIdeaCategories", action = "GetKeywordIdeaCategories")
    @WebResult(name = "GetKeywordIdeaCategoriesResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetKeywordIdeaCategoriesResponse getKeywordIdeaCategories(
        @WebParam(name = "GetKeywordIdeaCategoriesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordIdeaCategoriesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetKeywordIdeasResponse>
     */
    @WebMethod(operationName = "GetKeywordIdeas", action = "GetKeywordIdeas")
    public Response<GetKeywordIdeasResponse> getKeywordIdeasAsync(
        @WebParam(name = "GetKeywordIdeasRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordIdeasRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetKeywordIdeas", action = "GetKeywordIdeas")
    public Future<?> getKeywordIdeasAsync(
        @WebParam(name = "GetKeywordIdeasRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordIdeasRequest parameters,
        @WebParam(name = "GetKeywordIdeasResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetKeywordIdeasResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetKeywordIdeasResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetKeywordIdeas", action = "GetKeywordIdeas")
    @WebResult(name = "GetKeywordIdeasResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetKeywordIdeasResponse getKeywordIdeas(
        @WebParam(name = "GetKeywordIdeasRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordIdeasRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v11.adinsight.GetKeywordTrafficEstimatesResponse>
     */
    @WebMethod(operationName = "GetKeywordTrafficEstimates", action = "GetKeywordTrafficEstimates")
    public Response<GetKeywordTrafficEstimatesResponse> getKeywordTrafficEstimatesAsync(
        @WebParam(name = "GetKeywordTrafficEstimatesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordTrafficEstimatesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetKeywordTrafficEstimates", action = "GetKeywordTrafficEstimates")
    public Future<?> getKeywordTrafficEstimatesAsync(
        @WebParam(name = "GetKeywordTrafficEstimatesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordTrafficEstimatesRequest parameters,
        @WebParam(name = "GetKeywordTrafficEstimatesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetKeywordTrafficEstimatesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v11.adinsight.GetKeywordTrafficEstimatesResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetKeywordTrafficEstimates", action = "GetKeywordTrafficEstimates")
    @WebResult(name = "GetKeywordTrafficEstimatesResponse", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
    public GetKeywordTrafficEstimatesResponse getKeywordTrafficEstimates(
        @WebParam(name = "GetKeywordTrafficEstimatesRequest", targetNamespace = "Microsoft.Advertiser.AdInsight.Api.Service.V11", partName = "parameters")
        GetKeywordTrafficEstimatesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

}
