
package com.microsoft.bingads.v13.reporting;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ApiFaultDetail", targetNamespace = "https://bingads.microsoft.com/Reporting/v13")
public class ApiFaultDetail_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ApiFaultDetail faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ApiFaultDetail_Exception(String message, ApiFaultDetail faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public ApiFaultDetail_Exception(String message, ApiFaultDetail faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.microsoft.bingads.v13.reporting.ApiFaultDetail
     */
    public ApiFaultDetail getFaultInfo() {
        return faultInfo;
    }

}
