
package com.microsoft.bingads.v13.reporting;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ReportingService", targetNamespace = "https://bingads.microsoft.com/Reporting/v13", wsdlLocation = "https://reporting.api.sandbox.bingads.microsoft.com/Api/Advertiser/Reporting/v13/ReportingService.svc?wsdl")
public class ReportingService
    extends Service
{

    private static final URL REPORTINGSERVICE_WSDL_LOCATION;
    private static final WebServiceException REPORTINGSERVICE_EXCEPTION;
    private static final QName REPORTINGSERVICE_QNAME = new QName("https://bingads.microsoft.com/Reporting/v13", "ReportingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://reporting.api.sandbox.bingads.microsoft.com/Api/Advertiser/Reporting/v13/ReportingService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REPORTINGSERVICE_WSDL_LOCATION = url;
        REPORTINGSERVICE_EXCEPTION = e;
    }

    public ReportingService() {
        super(__getWsdlLocation(), REPORTINGSERVICE_QNAME);
    }

    public ReportingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REPORTINGSERVICE_QNAME, features);
    }

    public ReportingService(URL wsdlLocation) {
        super(wsdlLocation, REPORTINGSERVICE_QNAME);
    }

    public ReportingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REPORTINGSERVICE_QNAME, features);
    }

    public ReportingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReportingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IReportingService
     */
    @WebEndpoint(name = "BasicHttpBinding_IReportingService")
    public IReportingService getBasicHttpBindingIReportingService() {
        return super.getPort(new QName("https://bingads.microsoft.com/Reporting/v13", "BasicHttpBinding_IReportingService"), IReportingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IReportingService
     */
    @WebEndpoint(name = "BasicHttpBinding_IReportingService")
    public IReportingService getBasicHttpBindingIReportingService(WebServiceFeature... features) {
        return super.getPort(new QName("https://bingads.microsoft.com/Reporting/v13", "BasicHttpBinding_IReportingService"), IReportingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REPORTINGSERVICE_EXCEPTION!= null) {
            throw REPORTINGSERVICE_EXCEPTION;
        }
        return REPORTINGSERVICE_WSDL_LOCATION;
    }

}
