
package com.microsoft.bingads.v13.campaignmanagement;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AISearchSetting complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="AISearchSetting">
 *   <complexContent>
 *     <extension base="{https://bingads.microsoft.com/CampaignManagement/v13}Setting">
 *       <sequence>
 *         <element name="AISearchEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="AutoGeneratedImageOptOut" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="AutoGeneratedTextOptOut" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="FinalUrlExpansionOptOut" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="SearchTermMatchingOptOut" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AISearchSetting", propOrder = {
    "aiSearchEnabled",
    "autoGeneratedImageOptOut",
    "autoGeneratedTextOptOut",
    "finalUrlExpansionOptOut",
    "searchTermMatchingOptOut"
})
public class AISearchSetting
    extends Setting
{
    public AISearchSetting() {
      this.type = "AISearchSetting";
    }

    @XmlElement(name = "AISearchEnabled")
    protected Boolean aiSearchEnabled;
    @XmlElement(name = "AutoGeneratedImageOptOut", nillable = true)
    protected Boolean autoGeneratedImageOptOut;
    @XmlElement(name = "AutoGeneratedTextOptOut", nillable = true)
    protected Boolean autoGeneratedTextOptOut;
    @XmlElement(name = "FinalUrlExpansionOptOut", nillable = true)
    protected Boolean finalUrlExpansionOptOut;
    @XmlElement(name = "SearchTermMatchingOptOut", nillable = true)
    protected Boolean searchTermMatchingOptOut;

    /**
     * Gets the value of the aiSearchEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAISearchEnabled() {
        return aiSearchEnabled;
    }

    /**
     * Sets the value of the aiSearchEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAISearchEnabled(Boolean value) {
        this.aiSearchEnabled = value;
    }

    /**
     * Gets the value of the autoGeneratedImageOptOut property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAutoGeneratedImageOptOut() {
        return autoGeneratedImageOptOut;
    }

    /**
     * Sets the value of the autoGeneratedImageOptOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoGeneratedImageOptOut(Boolean value) {
        this.autoGeneratedImageOptOut = value;
    }

    /**
     * Gets the value of the autoGeneratedTextOptOut property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAutoGeneratedTextOptOut() {
        return autoGeneratedTextOptOut;
    }

    /**
     * Sets the value of the autoGeneratedTextOptOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoGeneratedTextOptOut(Boolean value) {
        this.autoGeneratedTextOptOut = value;
    }

    /**
     * Gets the value of the finalUrlExpansionOptOut property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getFinalUrlExpansionOptOut() {
        return finalUrlExpansionOptOut;
    }

    /**
     * Sets the value of the finalUrlExpansionOptOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFinalUrlExpansionOptOut(Boolean value) {
        this.finalUrlExpansionOptOut = value;
    }

    /**
     * Gets the value of the searchTermMatchingOptOut property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getSearchTermMatchingOptOut() {
        return searchTermMatchingOptOut;
    }

    /**
     * Sets the value of the searchTermMatchingOptOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSearchTermMatchingOptOut(Boolean value) {
        this.searchTermMatchingOptOut = value;
    }

}
