
package com.microsoft.bingads.v13.campaignmanagement;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "EditorialApiFaultDetail", targetNamespace = "https://bingads.microsoft.com/CampaignManagement/v13")
public class EditorialApiFaultDetail_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EditorialApiFaultDetail faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EditorialApiFaultDetail_Exception(String message, EditorialApiFaultDetail faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public EditorialApiFaultDetail_Exception(String message, EditorialApiFaultDetail faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.microsoft.bingads.v13.campaignmanagement.EditorialApiFaultDetail
     */
    public EditorialApiFaultDetail getFaultInfo() {
        return faultInfo;
    }

}
