
package com.microsoft.bingads.v13.campaignmanagement;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponsiveSearchAdsSetting complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ResponsiveSearchAdsSetting">
 *   <complexContent>
 *     <extension base="{https://bingads.microsoft.com/CampaignManagement/v13}Setting">
 *       <sequence>
 *         <element name="AutoGeneratedAssetsEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponsiveSearchAdsSetting", propOrder = {
    "autoGeneratedAssetsEnabled"
})
public class ResponsiveSearchAdsSetting
    extends Setting
{
    public ResponsiveSearchAdsSetting() {
      this.type = "ResponsiveSearchAdsSetting";
    }

    @XmlElement(name = "AutoGeneratedAssetsEnabled", nillable = true)
    protected Boolean autoGeneratedAssetsEnabled;

    /**
     * Gets the value of the autoGeneratedAssetsEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAutoGeneratedAssetsEnabled() {
        return autoGeneratedAssetsEnabled;
    }

    /**
     * Sets the value of the autoGeneratedAssetsEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAutoGeneratedAssetsEnabled(Boolean value) {
        this.autoGeneratedAssetsEnabled = value;
    }

}
