
package com.microsoft.bingads.v13.customerbilling;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ApiBatchFault", targetNamespace = "https://bingads.microsoft.com/Billing/v13")
public class ApiBatchFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ApiBatchFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ApiBatchFault_Exception(String message, ApiBatchFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public ApiBatchFault_Exception(String message, ApiBatchFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.microsoft.bingads.v13.customerbilling.ApiBatchFault
     */
    public ApiBatchFault getFaultInfo() {
        return faultInfo;
    }

}
