
package com.microsoft.bingads.v13.customerbilling;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CustomerBillingService", targetNamespace = "https://bingads.microsoft.com/Billing/v13", wsdlLocation = "https://clientcenter.api.sandbox.bingads.microsoft.com/Api/Billing/v13/CustomerBillingService.svc?wsdl")
public class CustomerBillingService
    extends Service
{

    private static final URL CUSTOMERBILLINGSERVICE_WSDL_LOCATION;
    private static final WebServiceException CUSTOMERBILLINGSERVICE_EXCEPTION;
    private static final QName CUSTOMERBILLINGSERVICE_QNAME = new QName("https://bingads.microsoft.com/Billing/v13", "CustomerBillingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://clientcenter.api.sandbox.bingads.microsoft.com/Api/Billing/v13/CustomerBillingService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERBILLINGSERVICE_WSDL_LOCATION = url;
        CUSTOMERBILLINGSERVICE_EXCEPTION = e;
    }

    public CustomerBillingService() {
        super(__getWsdlLocation(), CUSTOMERBILLINGSERVICE_QNAME);
    }

    public CustomerBillingService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERBILLINGSERVICE_QNAME, features);
    }

    public CustomerBillingService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERBILLINGSERVICE_QNAME);
    }

    public CustomerBillingService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERBILLINGSERVICE_QNAME, features);
    }

    public CustomerBillingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerBillingService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICustomerBillingService
     */
    @WebEndpoint(name = "BasicHttpBinding_ICustomerBillingService")
    public ICustomerBillingService getBasicHttpBindingICustomerBillingService() {
        return super.getPort(new QName("https://bingads.microsoft.com/Billing/v13", "BasicHttpBinding_ICustomerBillingService"), ICustomerBillingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICustomerBillingService
     */
    @WebEndpoint(name = "BasicHttpBinding_ICustomerBillingService")
    public ICustomerBillingService getBasicHttpBindingICustomerBillingService(WebServiceFeature... features) {
        return super.getPort(new QName("https://bingads.microsoft.com/Billing/v13", "BasicHttpBinding_ICustomerBillingService"), ICustomerBillingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERBILLINGSERVICE_EXCEPTION!= null) {
            throw CUSTOMERBILLINGSERVICE_EXCEPTION;
        }
        return CUSTOMERBILLINGSERVICE_WSDL_LOCATION;
    }

}
