
package com.microsoft.bingads.v13.customermanagement;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ApiFault", targetNamespace = "https://bingads.microsoft.com/Customer/v13")
public class ApiFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ApiFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ApiFault_Exception(String message, ApiFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public ApiFault_Exception(String message, ApiFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.microsoft.bingads.v13.customermanagement.ApiFault
     */
    public ApiFault getFaultInfo() {
        return faultInfo;
    }

}
