
package com.microsoft.bingads.v13.customermanagement;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ICustomerManagementService", targetNamespace = "https://bingads.microsoft.com/Customer/v13")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICustomerManagementService {


    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.GetAccountsInfoResponse>
     */
    @WebMethod(operationName = "GetAccountsInfo", action = "GetAccountsInfo")
    public Response<GetAccountsInfoResponse> getAccountsInfoAsync(
        @WebParam(name = "GetAccountsInfoRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetAccountsInfoRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAccountsInfo", action = "GetAccountsInfo")
    public Future<?> getAccountsInfoAsync(
        @WebParam(name = "GetAccountsInfoRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetAccountsInfoRequest parameters,
        @WebParam(name = "GetAccountsInfoResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAccountsInfoResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.GetAccountsInfoResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "GetAccountsInfo", action = "GetAccountsInfo")
    @WebResult(name = "GetAccountsInfoResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public GetAccountsInfoResponse getAccountsInfo(
        @WebParam(name = "GetAccountsInfoRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetAccountsInfoRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.FindAccountsResponse>
     */
    @WebMethod(operationName = "FindAccounts", action = "FindAccounts")
    public Response<FindAccountsResponse> findAccountsAsync(
        @WebParam(name = "FindAccountsRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        FindAccountsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "FindAccounts", action = "FindAccounts")
    public Future<?> findAccountsAsync(
        @WebParam(name = "FindAccountsRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        FindAccountsRequest parameters,
        @WebParam(name = "FindAccountsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<FindAccountsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.FindAccountsResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "FindAccounts", action = "FindAccounts")
    @WebResult(name = "FindAccountsResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public FindAccountsResponse findAccounts(
        @WebParam(name = "FindAccountsRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        FindAccountsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.AddAccountResponse>
     */
    @WebMethod(operationName = "AddAccount", action = "AddAccount")
    public Response<AddAccountResponse> addAccountAsync(
        @WebParam(name = "AddAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        AddAccountRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "AddAccount", action = "AddAccount")
    public Future<?> addAccountAsync(
        @WebParam(name = "AddAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        AddAccountRequest parameters,
        @WebParam(name = "AddAccountResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<AddAccountResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.AddAccountResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "AddAccount", action = "AddAccount")
    @WebResult(name = "AddAccountResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public AddAccountResponse addAccount(
        @WebParam(name = "AddAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        AddAccountRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.UpdateAccountResponse>
     */
    @WebMethod(operationName = "UpdateAccount", action = "UpdateAccount")
    public Response<UpdateAccountResponse> updateAccountAsync(
        @WebParam(name = "UpdateAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdateAccountRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "UpdateAccount", action = "UpdateAccount")
    public Future<?> updateAccountAsync(
        @WebParam(name = "UpdateAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdateAccountRequest parameters,
        @WebParam(name = "UpdateAccountResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<UpdateAccountResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.UpdateAccountResponse
     * @throws ApiFault_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "UpdateAccount", action = "UpdateAccount")
    @WebResult(name = "UpdateAccountResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public UpdateAccountResponse updateAccount(
        @WebParam(name = "UpdateAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdateAccountRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.GetCustomerResponse>
     */
    @WebMethod(operationName = "GetCustomer", action = "GetCustomer")
    public Response<GetCustomerResponse> getCustomerAsync(
        @WebParam(name = "GetCustomerRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetCustomerRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetCustomer", action = "GetCustomer")
    public Future<?> getCustomerAsync(
        @WebParam(name = "GetCustomerRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetCustomerRequest parameters,
        @WebParam(name = "GetCustomerResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCustomerResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.GetCustomerResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "GetCustomer", action = "GetCustomer")
    @WebResult(name = "GetCustomerResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public GetCustomerResponse getCustomer(
        @WebParam(name = "GetCustomerRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetCustomerRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.UpdateCustomerResponse>
     */
    @WebMethod(operationName = "UpdateCustomer", action = "UpdateCustomer")
    public Response<UpdateCustomerResponse> updateCustomerAsync(
        @WebParam(name = "UpdateCustomerRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdateCustomerRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "UpdateCustomer", action = "UpdateCustomer")
    public Future<?> updateCustomerAsync(
        @WebParam(name = "UpdateCustomerRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdateCustomerRequest parameters,
        @WebParam(name = "UpdateCustomerResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<UpdateCustomerResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.UpdateCustomerResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "UpdateCustomer", action = "UpdateCustomer")
    @WebResult(name = "UpdateCustomerResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public UpdateCustomerResponse updateCustomer(
        @WebParam(name = "UpdateCustomerRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdateCustomerRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.SignupCustomerResponse>
     */
    @WebMethod(operationName = "SignupCustomer", action = "SignupCustomer")
    public Response<SignupCustomerResponse> signupCustomerAsync(
        @WebParam(name = "SignupCustomerRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SignupCustomerRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SignupCustomer", action = "SignupCustomer")
    public Future<?> signupCustomerAsync(
        @WebParam(name = "SignupCustomerRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SignupCustomerRequest parameters,
        @WebParam(name = "SignupCustomerResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SignupCustomerResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.SignupCustomerResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "SignupCustomer", action = "SignupCustomer")
    @WebResult(name = "SignupCustomerResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public SignupCustomerResponse signupCustomer(
        @WebParam(name = "SignupCustomerRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SignupCustomerRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.GetAccountResponse>
     */
    @WebMethod(operationName = "GetAccount", action = "GetAccount")
    public Response<GetAccountResponse> getAccountAsync(
        @WebParam(name = "GetAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetAccountRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAccount", action = "GetAccount")
    public Future<?> getAccountAsync(
        @WebParam(name = "GetAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetAccountRequest parameters,
        @WebParam(name = "GetAccountResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAccountResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.GetAccountResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "GetAccount", action = "GetAccount")
    @WebResult(name = "GetAccountResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public GetAccountResponse getAccount(
        @WebParam(name = "GetAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetAccountRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.GetCustomersInfoResponse>
     */
    @WebMethod(operationName = "GetCustomersInfo", action = "GetCustomersInfo")
    public Response<GetCustomersInfoResponse> getCustomersInfoAsync(
        @WebParam(name = "GetCustomersInfoRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetCustomersInfoRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetCustomersInfo", action = "GetCustomersInfo")
    public Future<?> getCustomersInfoAsync(
        @WebParam(name = "GetCustomersInfoRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetCustomersInfoRequest parameters,
        @WebParam(name = "GetCustomersInfoResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCustomersInfoResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.GetCustomersInfoResponse
     * @throws ApiFault_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetCustomersInfo", action = "GetCustomersInfo")
    @WebResult(name = "GetCustomersInfoResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public GetCustomersInfoResponse getCustomersInfo(
        @WebParam(name = "GetCustomersInfoRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetCustomersInfoRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.DeleteAccountResponse>
     */
    @WebMethod(operationName = "DeleteAccount", action = "DeleteAccount")
    public Response<DeleteAccountResponse> deleteAccountAsync(
        @WebParam(name = "DeleteAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        DeleteAccountRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DeleteAccount", action = "DeleteAccount")
    public Future<?> deleteAccountAsync(
        @WebParam(name = "DeleteAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        DeleteAccountRequest parameters,
        @WebParam(name = "DeleteAccountResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DeleteAccountResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.DeleteAccountResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "DeleteAccount", action = "DeleteAccount")
    @WebResult(name = "DeleteAccountResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public DeleteAccountResponse deleteAccount(
        @WebParam(name = "DeleteAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        DeleteAccountRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.DeleteCustomerResponse>
     */
    @WebMethod(operationName = "DeleteCustomer", action = "DeleteCustomer")
    public Response<DeleteCustomerResponse> deleteCustomerAsync(
        @WebParam(name = "DeleteCustomerRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        DeleteCustomerRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DeleteCustomer", action = "DeleteCustomer")
    public Future<?> deleteCustomerAsync(
        @WebParam(name = "DeleteCustomerRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        DeleteCustomerRequest parameters,
        @WebParam(name = "DeleteCustomerResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DeleteCustomerResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.DeleteCustomerResponse
     * @throws ApiFault_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "DeleteCustomer", action = "DeleteCustomer")
    @WebResult(name = "DeleteCustomerResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public DeleteCustomerResponse deleteCustomer(
        @WebParam(name = "DeleteCustomerRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        DeleteCustomerRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.UpdateUserResponse>
     */
    @WebMethod(operationName = "UpdateUser", action = "UpdateUser")
    public Response<UpdateUserResponse> updateUserAsync(
        @WebParam(name = "UpdateUserRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdateUserRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "UpdateUser", action = "UpdateUser")
    public Future<?> updateUserAsync(
        @WebParam(name = "UpdateUserRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdateUserRequest parameters,
        @WebParam(name = "UpdateUserResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<UpdateUserResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.UpdateUserResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "UpdateUser", action = "UpdateUser")
    @WebResult(name = "UpdateUserResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public UpdateUserResponse updateUser(
        @WebParam(name = "UpdateUserRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdateUserRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.UpdateUserRolesResponse>
     */
    @WebMethod(operationName = "UpdateUserRoles", action = "UpdateUserRoles")
    public Response<UpdateUserRolesResponse> updateUserRolesAsync(
        @WebParam(name = "UpdateUserRolesRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdateUserRolesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "UpdateUserRoles", action = "UpdateUserRoles")
    public Future<?> updateUserRolesAsync(
        @WebParam(name = "UpdateUserRolesRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdateUserRolesRequest parameters,
        @WebParam(name = "UpdateUserRolesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<UpdateUserRolesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.UpdateUserRolesResponse
     * @throws ApiFault_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "UpdateUserRoles", action = "UpdateUserRoles")
    @WebResult(name = "UpdateUserRolesResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public UpdateUserRolesResponse updateUserRoles(
        @WebParam(name = "UpdateUserRolesRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdateUserRolesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.GetUserResponse>
     */
    @WebMethod(operationName = "GetUser", action = "GetUser")
    public Response<GetUserResponse> getUserAsync(
        @WebParam(name = "GetUserRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetUserRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetUser", action = "GetUser")
    public Future<?> getUserAsync(
        @WebParam(name = "GetUserRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetUserRequest parameters,
        @WebParam(name = "GetUserResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetUserResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.GetUserResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "GetUser", action = "GetUser")
    @WebResult(name = "GetUserResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public GetUserResponse getUser(
        @WebParam(name = "GetUserRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetUserRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.GetCurrentUserResponse>
     */
    @WebMethod(operationName = "GetCurrentUser", action = "GetCurrentUser")
    public Response<GetCurrentUserResponse> getCurrentUserAsync(
        @WebParam(name = "GetCurrentUserRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetCurrentUserRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetCurrentUser", action = "GetCurrentUser")
    public Future<?> getCurrentUserAsync(
        @WebParam(name = "GetCurrentUserRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetCurrentUserRequest parameters,
        @WebParam(name = "GetCurrentUserResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCurrentUserResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.GetCurrentUserResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "GetCurrentUser", action = "GetCurrentUser")
    @WebResult(name = "GetCurrentUserResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public GetCurrentUserResponse getCurrentUser(
        @WebParam(name = "GetCurrentUserRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetCurrentUserRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.DeleteUserResponse>
     */
    @WebMethod(operationName = "DeleteUser", action = "DeleteUser")
    public Response<DeleteUserResponse> deleteUserAsync(
        @WebParam(name = "DeleteUserRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        DeleteUserRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "DeleteUser", action = "DeleteUser")
    public Future<?> deleteUserAsync(
        @WebParam(name = "DeleteUserRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        DeleteUserRequest parameters,
        @WebParam(name = "DeleteUserResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<DeleteUserResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.DeleteUserResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "DeleteUser", action = "DeleteUser")
    @WebResult(name = "DeleteUserResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public DeleteUserResponse deleteUser(
        @WebParam(name = "DeleteUserRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        DeleteUserRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.GetUsersInfoResponse>
     */
    @WebMethod(operationName = "GetUsersInfo", action = "GetUsersInfo")
    public Response<GetUsersInfoResponse> getUsersInfoAsync(
        @WebParam(name = "GetUsersInfoRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetUsersInfoRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetUsersInfo", action = "GetUsersInfo")
    public Future<?> getUsersInfoAsync(
        @WebParam(name = "GetUsersInfoRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetUsersInfoRequest parameters,
        @WebParam(name = "GetUsersInfoResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetUsersInfoResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.GetUsersInfoResponse
     * @throws ApiFault_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetUsersInfo", action = "GetUsersInfo")
    @WebResult(name = "GetUsersInfoResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public GetUsersInfoResponse getUsersInfo(
        @WebParam(name = "GetUsersInfoRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetUsersInfoRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.GetCustomerPilotFeaturesResponse>
     */
    @WebMethod(operationName = "GetCustomerPilotFeatures", action = "GetCustomerPilotFeatures")
    public Response<GetCustomerPilotFeaturesResponse> getCustomerPilotFeaturesAsync(
        @WebParam(name = "GetCustomerPilotFeaturesRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetCustomerPilotFeaturesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetCustomerPilotFeatures", action = "GetCustomerPilotFeatures")
    public Future<?> getCustomerPilotFeaturesAsync(
        @WebParam(name = "GetCustomerPilotFeaturesRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetCustomerPilotFeaturesRequest parameters,
        @WebParam(name = "GetCustomerPilotFeaturesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCustomerPilotFeaturesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.GetCustomerPilotFeaturesResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "GetCustomerPilotFeatures", action = "GetCustomerPilotFeatures")
    @WebResult(name = "GetCustomerPilotFeaturesResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public GetCustomerPilotFeaturesResponse getCustomerPilotFeatures(
        @WebParam(name = "GetCustomerPilotFeaturesRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetCustomerPilotFeaturesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.GetAccountPilotFeaturesResponse>
     */
    @WebMethod(operationName = "GetAccountPilotFeatures", action = "GetAccountPilotFeatures")
    public Response<GetAccountPilotFeaturesResponse> getAccountPilotFeaturesAsync(
        @WebParam(name = "GetAccountPilotFeaturesRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetAccountPilotFeaturesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAccountPilotFeatures", action = "GetAccountPilotFeatures")
    public Future<?> getAccountPilotFeaturesAsync(
        @WebParam(name = "GetAccountPilotFeaturesRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetAccountPilotFeaturesRequest parameters,
        @WebParam(name = "GetAccountPilotFeaturesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAccountPilotFeaturesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.GetAccountPilotFeaturesResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "GetAccountPilotFeatures", action = "GetAccountPilotFeatures")
    @WebResult(name = "GetAccountPilotFeaturesResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public GetAccountPilotFeaturesResponse getAccountPilotFeatures(
        @WebParam(name = "GetAccountPilotFeaturesRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetAccountPilotFeaturesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.GetPilotFeaturesCountriesResponse>
     */
    @WebMethod(operationName = "GetPilotFeaturesCountries", action = "GetPilotFeaturesCountries")
    public Response<GetPilotFeaturesCountriesResponse> getPilotFeaturesCountriesAsync(
        @WebParam(name = "GetPilotFeaturesCountriesRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetPilotFeaturesCountriesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetPilotFeaturesCountries", action = "GetPilotFeaturesCountries")
    public Future<?> getPilotFeaturesCountriesAsync(
        @WebParam(name = "GetPilotFeaturesCountriesRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetPilotFeaturesCountriesRequest parameters,
        @WebParam(name = "GetPilotFeaturesCountriesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPilotFeaturesCountriesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.GetPilotFeaturesCountriesResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "GetPilotFeaturesCountries", action = "GetPilotFeaturesCountries")
    @WebResult(name = "GetPilotFeaturesCountriesResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public GetPilotFeaturesCountriesResponse getPilotFeaturesCountries(
        @WebParam(name = "GetPilotFeaturesCountriesRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetPilotFeaturesCountriesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.GetAccessibleCustomerResponse>
     */
    @WebMethod(operationName = "GetAccessibleCustomer", action = "GetAccessibleCustomer")
    public Response<GetAccessibleCustomerResponse> getAccessibleCustomerAsync(
        @WebParam(name = "GetAccessibleCustomerRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetAccessibleCustomerRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAccessibleCustomer", action = "GetAccessibleCustomer")
    public Future<?> getAccessibleCustomerAsync(
        @WebParam(name = "GetAccessibleCustomerRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetAccessibleCustomerRequest parameters,
        @WebParam(name = "GetAccessibleCustomerResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAccessibleCustomerResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.GetAccessibleCustomerResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "GetAccessibleCustomer", action = "GetAccessibleCustomer")
    @WebResult(name = "GetAccessibleCustomerResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public GetAccessibleCustomerResponse getAccessibleCustomer(
        @WebParam(name = "GetAccessibleCustomerRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetAccessibleCustomerRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.FindAccountsOrCustomersInfoResponse>
     */
    @WebMethod(operationName = "FindAccountsOrCustomersInfo", action = "FindAccountsOrCustomersInfo")
    public Response<FindAccountsOrCustomersInfoResponse> findAccountsOrCustomersInfoAsync(
        @WebParam(name = "FindAccountsOrCustomersInfoRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        FindAccountsOrCustomersInfoRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "FindAccountsOrCustomersInfo", action = "FindAccountsOrCustomersInfo")
    public Future<?> findAccountsOrCustomersInfoAsync(
        @WebParam(name = "FindAccountsOrCustomersInfoRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        FindAccountsOrCustomersInfoRequest parameters,
        @WebParam(name = "FindAccountsOrCustomersInfoResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<FindAccountsOrCustomersInfoResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.FindAccountsOrCustomersInfoResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "FindAccountsOrCustomersInfo", action = "FindAccountsOrCustomersInfo")
    @WebResult(name = "FindAccountsOrCustomersInfoResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public FindAccountsOrCustomersInfoResponse findAccountsOrCustomersInfo(
        @WebParam(name = "FindAccountsOrCustomersInfoRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        FindAccountsOrCustomersInfoRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.UpgradeCustomerToAgencyResponse>
     */
    @WebMethod(operationName = "UpgradeCustomerToAgency", action = "UpgradeCustomerToAgency")
    public Response<UpgradeCustomerToAgencyResponse> upgradeCustomerToAgencyAsync(
        @WebParam(name = "UpgradeCustomerToAgencyRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpgradeCustomerToAgencyRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "UpgradeCustomerToAgency", action = "UpgradeCustomerToAgency")
    public Future<?> upgradeCustomerToAgencyAsync(
        @WebParam(name = "UpgradeCustomerToAgencyRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpgradeCustomerToAgencyRequest parameters,
        @WebParam(name = "UpgradeCustomerToAgencyResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<UpgradeCustomerToAgencyResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.UpgradeCustomerToAgencyResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "UpgradeCustomerToAgency", action = "UpgradeCustomerToAgency")
    @WebResult(name = "UpgradeCustomerToAgencyResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public UpgradeCustomerToAgencyResponse upgradeCustomerToAgency(
        @WebParam(name = "UpgradeCustomerToAgencyRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpgradeCustomerToAgencyRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.AddPrepayAccountResponse>
     */
    @WebMethod(operationName = "AddPrepayAccount", action = "AddPrepayAccount")
    public Response<AddPrepayAccountResponse> addPrepayAccountAsync(
        @WebParam(name = "AddPrepayAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        AddPrepayAccountRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "AddPrepayAccount", action = "AddPrepayAccount")
    public Future<?> addPrepayAccountAsync(
        @WebParam(name = "AddPrepayAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        AddPrepayAccountRequest parameters,
        @WebParam(name = "AddPrepayAccountResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<AddPrepayAccountResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.AddPrepayAccountResponse
     * @throws ApiFault_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "AddPrepayAccount", action = "AddPrepayAccount")
    @WebResult(name = "AddPrepayAccountResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public AddPrepayAccountResponse addPrepayAccount(
        @WebParam(name = "AddPrepayAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        AddPrepayAccountRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.UpdatePrepayAccountResponse>
     */
    @WebMethod(operationName = "UpdatePrepayAccount", action = "UpdatePrepayAccount")
    public Response<UpdatePrepayAccountResponse> updatePrepayAccountAsync(
        @WebParam(name = "UpdatePrepayAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdatePrepayAccountRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "UpdatePrepayAccount", action = "UpdatePrepayAccount")
    public Future<?> updatePrepayAccountAsync(
        @WebParam(name = "UpdatePrepayAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdatePrepayAccountRequest parameters,
        @WebParam(name = "UpdatePrepayAccountResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<UpdatePrepayAccountResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.UpdatePrepayAccountResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "UpdatePrepayAccount", action = "UpdatePrepayAccount")
    @WebResult(name = "UpdatePrepayAccountResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public UpdatePrepayAccountResponse updatePrepayAccount(
        @WebParam(name = "UpdatePrepayAccountRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdatePrepayAccountRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.MapCustomerIdToExternalCustomerIdResponse>
     */
    @WebMethod(operationName = "MapCustomerIdToExternalCustomerId", action = "MapCustomerIdToExternalCustomerId")
    public Response<MapCustomerIdToExternalCustomerIdResponse> mapCustomerIdToExternalCustomerIdAsync(
        @WebParam(name = "MapCustomerIdToExternalCustomerIdRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        MapCustomerIdToExternalCustomerIdRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "MapCustomerIdToExternalCustomerId", action = "MapCustomerIdToExternalCustomerId")
    public Future<?> mapCustomerIdToExternalCustomerIdAsync(
        @WebParam(name = "MapCustomerIdToExternalCustomerIdRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        MapCustomerIdToExternalCustomerIdRequest parameters,
        @WebParam(name = "MapCustomerIdToExternalCustomerIdResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<MapCustomerIdToExternalCustomerIdResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.MapCustomerIdToExternalCustomerIdResponse
     * @throws ApiFault_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "MapCustomerIdToExternalCustomerId", action = "MapCustomerIdToExternalCustomerId")
    @WebResult(name = "MapCustomerIdToExternalCustomerIdResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public MapCustomerIdToExternalCustomerIdResponse mapCustomerIdToExternalCustomerId(
        @WebParam(name = "MapCustomerIdToExternalCustomerIdRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        MapCustomerIdToExternalCustomerIdRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.MapAccountIdToExternalAccountIdsResponse>
     */
    @WebMethod(operationName = "MapAccountIdToExternalAccountIds", action = "MapAccountIdToExternalAccountIds")
    public Response<MapAccountIdToExternalAccountIdsResponse> mapAccountIdToExternalAccountIdsAsync(
        @WebParam(name = "MapAccountIdToExternalAccountIdsRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        MapAccountIdToExternalAccountIdsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "MapAccountIdToExternalAccountIds", action = "MapAccountIdToExternalAccountIds")
    public Future<?> mapAccountIdToExternalAccountIdsAsync(
        @WebParam(name = "MapAccountIdToExternalAccountIdsRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        MapAccountIdToExternalAccountIdsRequest parameters,
        @WebParam(name = "MapAccountIdToExternalAccountIdsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<MapAccountIdToExternalAccountIdsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.MapAccountIdToExternalAccountIdsResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "MapAccountIdToExternalAccountIds", action = "MapAccountIdToExternalAccountIds")
    @WebResult(name = "MapAccountIdToExternalAccountIdsResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public MapAccountIdToExternalAccountIdsResponse mapAccountIdToExternalAccountIds(
        @WebParam(name = "MapAccountIdToExternalAccountIdsRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        MapAccountIdToExternalAccountIdsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.SearchCustomersResponse>
     */
    @WebMethod(operationName = "SearchCustomers", action = "SearchCustomers")
    public Response<SearchCustomersResponse> searchCustomersAsync(
        @WebParam(name = "SearchCustomersRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SearchCustomersRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SearchCustomers", action = "SearchCustomers")
    public Future<?> searchCustomersAsync(
        @WebParam(name = "SearchCustomersRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SearchCustomersRequest parameters,
        @WebParam(name = "SearchCustomersResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SearchCustomersResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.SearchCustomersResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "SearchCustomers", action = "SearchCustomers")
    @WebResult(name = "SearchCustomersResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public SearchCustomersResponse searchCustomers(
        @WebParam(name = "SearchCustomersRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SearchCustomersRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.AddClientLinksResponse>
     */
    @WebMethod(operationName = "AddClientLinks", action = "AddClientLinks")
    public Response<AddClientLinksResponse> addClientLinksAsync(
        @WebParam(name = "AddClientLinksRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        AddClientLinksRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "AddClientLinks", action = "AddClientLinks")
    public Future<?> addClientLinksAsync(
        @WebParam(name = "AddClientLinksRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        AddClientLinksRequest parameters,
        @WebParam(name = "AddClientLinksResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<AddClientLinksResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.AddClientLinksResponse
     * @throws ApiFault_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "AddClientLinks", action = "AddClientLinks")
    @WebResult(name = "AddClientLinksResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public AddClientLinksResponse addClientLinks(
        @WebParam(name = "AddClientLinksRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        AddClientLinksRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.UpdateClientLinksResponse>
     */
    @WebMethod(operationName = "UpdateClientLinks", action = "UpdateClientLinks")
    public Response<UpdateClientLinksResponse> updateClientLinksAsync(
        @WebParam(name = "UpdateClientLinksRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdateClientLinksRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "UpdateClientLinks", action = "UpdateClientLinks")
    public Future<?> updateClientLinksAsync(
        @WebParam(name = "UpdateClientLinksRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdateClientLinksRequest parameters,
        @WebParam(name = "UpdateClientLinksResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<UpdateClientLinksResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.UpdateClientLinksResponse
     * @throws ApiFault_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "UpdateClientLinks", action = "UpdateClientLinks")
    @WebResult(name = "UpdateClientLinksResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public UpdateClientLinksResponse updateClientLinks(
        @WebParam(name = "UpdateClientLinksRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        UpdateClientLinksRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.SearchClientLinksResponse>
     */
    @WebMethod(operationName = "SearchClientLinks", action = "SearchClientLinks")
    public Response<SearchClientLinksResponse> searchClientLinksAsync(
        @WebParam(name = "SearchClientLinksRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SearchClientLinksRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SearchClientLinks", action = "SearchClientLinks")
    public Future<?> searchClientLinksAsync(
        @WebParam(name = "SearchClientLinksRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SearchClientLinksRequest parameters,
        @WebParam(name = "SearchClientLinksResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SearchClientLinksResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.SearchClientLinksResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "SearchClientLinks", action = "SearchClientLinks")
    @WebResult(name = "SearchClientLinksResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public SearchClientLinksResponse searchClientLinks(
        @WebParam(name = "SearchClientLinksRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SearchClientLinksRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.SearchAccountsResponse>
     */
    @WebMethod(operationName = "SearchAccounts", action = "SearchAccounts")
    public Response<SearchAccountsResponse> searchAccountsAsync(
        @WebParam(name = "SearchAccountsRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SearchAccountsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SearchAccounts", action = "SearchAccounts")
    public Future<?> searchAccountsAsync(
        @WebParam(name = "SearchAccountsRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SearchAccountsRequest parameters,
        @WebParam(name = "SearchAccountsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SearchAccountsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.SearchAccountsResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "SearchAccounts", action = "SearchAccounts")
    @WebResult(name = "SearchAccountsResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public SearchAccountsResponse searchAccounts(
        @WebParam(name = "SearchAccountsRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SearchAccountsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.SendUserInvitationResponse>
     */
    @WebMethod(operationName = "SendUserInvitation", action = "SendUserInvitation")
    public Response<SendUserInvitationResponse> sendUserInvitationAsync(
        @WebParam(name = "SendUserInvitationRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SendUserInvitationRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SendUserInvitation", action = "SendUserInvitation")
    public Future<?> sendUserInvitationAsync(
        @WebParam(name = "SendUserInvitationRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SendUserInvitationRequest parameters,
        @WebParam(name = "SendUserInvitationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SendUserInvitationResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.SendUserInvitationResponse
     * @throws ApiFault_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "SendUserInvitation", action = "SendUserInvitation")
    @WebResult(name = "SendUserInvitationResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public SendUserInvitationResponse sendUserInvitation(
        @WebParam(name = "SendUserInvitationRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SendUserInvitationRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.SearchUserInvitationsResponse>
     */
    @WebMethod(operationName = "SearchUserInvitations", action = "SearchUserInvitations")
    public Response<SearchUserInvitationsResponse> searchUserInvitationsAsync(
        @WebParam(name = "SearchUserInvitationsRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SearchUserInvitationsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SearchUserInvitations", action = "SearchUserInvitations")
    public Future<?> searchUserInvitationsAsync(
        @WebParam(name = "SearchUserInvitationsRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SearchUserInvitationsRequest parameters,
        @WebParam(name = "SearchUserInvitationsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SearchUserInvitationsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.SearchUserInvitationsResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "SearchUserInvitations", action = "SearchUserInvitations")
    @WebResult(name = "SearchUserInvitationsResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public SearchUserInvitationsResponse searchUserInvitations(
        @WebParam(name = "SearchUserInvitationsRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        SearchUserInvitationsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.ValidateAddressResponse>
     */
    @WebMethod(operationName = "ValidateAddress", action = "ValidateAddress")
    public Response<ValidateAddressResponse> validateAddressAsync(
        @WebParam(name = "ValidateAddressRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        ValidateAddressRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "ValidateAddress", action = "ValidateAddress")
    public Future<?> validateAddressAsync(
        @WebParam(name = "ValidateAddressRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        ValidateAddressRequest parameters,
        @WebParam(name = "ValidateAddressResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<ValidateAddressResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.ValidateAddressResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "ValidateAddress", action = "ValidateAddress")
    @WebResult(name = "ValidateAddressResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public ValidateAddressResponse validateAddress(
        @WebParam(name = "ValidateAddressRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        ValidateAddressRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.GetLinkedAccountsAndCustomersInfoResponse>
     */
    @WebMethod(operationName = "GetLinkedAccountsAndCustomersInfo", action = "GetLinkedAccountsAndCustomersInfo")
    public Response<GetLinkedAccountsAndCustomersInfoResponse> getLinkedAccountsAndCustomersInfoAsync(
        @WebParam(name = "GetLinkedAccountsAndCustomersInfoRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetLinkedAccountsAndCustomersInfoRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetLinkedAccountsAndCustomersInfo", action = "GetLinkedAccountsAndCustomersInfo")
    public Future<?> getLinkedAccountsAndCustomersInfoAsync(
        @WebParam(name = "GetLinkedAccountsAndCustomersInfoRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetLinkedAccountsAndCustomersInfoRequest parameters,
        @WebParam(name = "GetLinkedAccountsAndCustomersInfoResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetLinkedAccountsAndCustomersInfoResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.GetLinkedAccountsAndCustomersInfoResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "GetLinkedAccountsAndCustomersInfo", action = "GetLinkedAccountsAndCustomersInfo")
    @WebResult(name = "GetLinkedAccountsAndCustomersInfoResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public GetLinkedAccountsAndCustomersInfoResponse getLinkedAccountsAndCustomersInfo(
        @WebParam(name = "GetLinkedAccountsAndCustomersInfoRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetLinkedAccountsAndCustomersInfoRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.v13.customermanagement.GetUserMFAStatusResponse>
     */
    @WebMethod(operationName = "GetUserMFAStatus", action = "GetUserMFAStatus")
    public Response<GetUserMFAStatusResponse> getUserMFAStatusAsync(
        @WebParam(name = "GetUserMFAStatusRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetUserMFAStatusRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetUserMFAStatus", action = "GetUserMFAStatus")
    public Future<?> getUserMFAStatusAsync(
        @WebParam(name = "GetUserMFAStatusRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetUserMFAStatusRequest parameters,
        @WebParam(name = "GetUserMFAStatusResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetUserMFAStatusResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.v13.customermanagement.GetUserMFAStatusResponse
     * @throws AdApiFaultDetail_Exception
     * @throws ApiFault_Exception
     */
    @WebMethod(operationName = "GetUserMFAStatus", action = "GetUserMFAStatus")
    @WebResult(name = "GetUserMFAStatusResponse", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
    public GetUserMFAStatusResponse getUserMFAStatus(
        @WebParam(name = "GetUserMFAStatusRequest", targetNamespace = "https://bingads.microsoft.com/Customer/v13", partName = "parameters")
        GetUserMFAStatusRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFault_Exception
    ;

}
