package com.microsoft.bingads.v13.api.test.entities.campaign.read;

import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

import com.microsoft.bingads.internal.functionalinterfaces.Function;
import com.microsoft.bingads.v13.api.test.entities.ObjectComparer;
import com.microsoft.bingads.v13.api.test.entities.campaign.BulkCampaignTest;
import com.microsoft.bingads.v13.bulk.entities.BulkCampaign;
import com.microsoft.bingads.v13.campaignmanagement.ArrayOflong;
import com.microsoft.bingads.v13.campaignmanagement.PerformanceMaxSetting;
import com.microsoft.bingads.v13.campaignmanagement.Setting;

@RunWith(Parameterized.class)
public class BulkCampaignReadFromRowValuesPerformanceMaxSettingsTest extends BulkCampaignTest {

    @Parameterized.Parameter(value = 1)
    public String finalUrlExpansionOptOut;
    
    @Parameterized.Parameter(value = 2)
    public String autoGeneratedTextOptOut;
    
    @Parameterized.Parameter(value = 3)
    public String autoGeneratedImageOptOut;
    
    @Parameterized.Parameter(value = 4)
    public String pageFeedIds;
    
    @Parameterized.Parameter(value = 5)
    public String costPerSaleOptOut;
    
    @Parameterized.Parameter(value = 6)
    public List<Setting> expectedResult;
    
    

    @Parameterized.Parameters
    public static Collection<Object[]> data() {       
    	PerformanceMaxSetting setting1 = new PerformanceMaxSetting();
    	ArrayOflong pids = new ArrayOflong();
        pids.getLongs().addAll(Arrays.asList(1L, 2L, 3L, 4L));
        setting1.setFinalUrlExpansionOptOut(true);
        setting1.setAutoGeneratedTextOptOut(true);
        setting1.setAutoGeneratedImageOptOut(false);
        setting1.setCostPerSaleOptOut(false);
        setting1.setPageFeedIds(pids);
        setting1.setType("PerformanceMaxSetting");
        
        PerformanceMaxSetting setting2 = new PerformanceMaxSetting();
        ArrayOflong pids2 = new ArrayOflong();
        pids2.getLongs().addAll(Arrays.asList(101L, 102L, 103L, 104L));
        setting2.setFinalUrlExpansionOptOut(false);
        setting2.setAutoGeneratedTextOptOut(false);
        setting2.setAutoGeneratedImageOptOut(false);
        setting2.setCostPerSaleOptOut(true);
        setting2.setPageFeedIds(pids2);
        setting2.setType("PerformanceMaxSetting");

        return Arrays.asList(
                new Object[][]{
                        {"PerformanceMax", "true", "true", "false", "1;2;3;4", "false", Collections.singletonList(setting1)},
                        {"PerformanceMax", "false", "false", "false", "101;102;103;104", "true", Collections.singletonList(setting2)},
                }
        );
    }

    @Test
    public void testRead() {
        Map<String, String> values = new HashMap<String, String>();

        values.put("Campaign Type", datum);
        values.put("Url Expansion Opt Out", finalUrlExpansionOptOut);
        values.put("Auto Generated Text Assets Opt Out", autoGeneratedTextOptOut);
        values.put("Auto Generated Image Assets Opt Out", autoGeneratedImageOptOut);
        values.put("Page Feed Ids", pageFeedIds);
        values.put("Cost Per Sale Opt Out", costPerSaleOptOut);

        testReadProperty(
                values,
                this.expectedResult,
                new Function<BulkCampaign, List<Setting>>() {
                    @Override
                    public List<Setting> apply(BulkCampaign c) {
                        if (c.getCampaign().getSettings() == null) {
                            return null;
                        }
                        
                        return c.getCampaign().getSettings().getSettings().stream().filter(s -> s.getClass() == PerformanceMaxSetting.class).collect(Collectors.toList());
                    }
                },
                new ObjectComparer<List<Setting>>()
        );
    }
}
