package com.microsoft.bingads.v13.api.test.entities.campaign;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

import com.microsoft.bingads.v13.api.test.entities.campaign.write.*;

@RunWith(Suite.class)
@SuiteClasses({
        BulkCampaignWriteToRowValuesAccountIdTest.class,
        BulkCampaignWriteToRowValuesBudgetTypeTest.class,
        BulkCampaignWriteToRowValuesDailyBudgetTest.class,
        BulkCampaignWriteToRowValuesIdTest.class,
        BulkCampaignWriteToRowValuesNameTest.class,
        BulkCampaignWriteToRowValuesStatusTest.class,
        BulkCampaignWriteToRowValuesTimeZoneTest.class,
        BulkCampaignWriteToRowValuesAudienceAdsBidAdjustmentTest.class,
        BulkCampaignWriteToRowValuesCampaignTypeTest.class,
        //BulkCampaignWriteToRowValuesDetailsVerifiedTrackingSettingTest.class,
        BulkCampaignWriteToRowValuesDisclaimerAdsEnabledDisclaimerSettingTest.class,
        BulkCampaignWriteToRowValuesStoreIdShoppingSettingTest.class,
        BulkCampaignWriteToRowValuesStoreIdOtherSettingTest.class,
        BulkCampaignWriteToRowValuesPriorityShoppingSettingTest.class,
        BulkCampaignWriteToRowValuesPriorityOtherSettingTest.class,
        BulkCampaignWriteToRowValuesCountryCodeShoppingSettingTest.class,
        BulkCampaignWriteToRowValuesCountryCodeOtherSettingTest.class,
        BulkCampaignWriteToRowValuesBidStrategyTypeTest.class,
        BulkCampaignWriteToRowValuesWebsiteDSASettingTest.class,
        BulkCampaignWriteToRowValuesWebsiteOtherSettingTest.class,
        BulkCampaignWriteToRowValuesDomainLanguageDSASettingTest.class,
        BulkCampaignWriteToRowValuesDomainLanguageOtherSettingTest.class,
        BulkCampaignWriteToRowValuesDynamicDescriptionEnabledDSASettingTest.class,
        BulkCampaignWriteToRowValuesSourceDSASettingTest.class,
        BulkCampaignWriteToRowValuesExperimentIdTest.class,
        BulkCampaignWriteToRowValuesFinalUrlSuffixTest.class,
        BulkCampaignWriteToRowValuesPageFeedIdsDSASettingTest.class,
        BulkCampaignWriteAdScheduleUseSearcherTimeZone.class,
        BulkCampaignWriteToRowValuesBidStrategyIdTest.class,
        BulkCampaignWriteToRowValuesBidStrategyIdTest.class,
        BulkCampaignWriteToRowValuesFeedIdAudienceSettingTest.class,
        BulkCampaignWriteToRowValuesMultiMediaAdBidAdjustmentTest.class,
        BulkCampaignWriteToRowValuesPerformanceMaxSettingTest.class,
        BulkCampaignWriteToRowValuesIsMultiChannelCampaignTest.class,
        BulkCampaignWriteToRowValuesDestinationChannelTest.class,
        BulkCampaignWriteToRowValuesAutoGeneratedImageOptOutTest.class,
        BulkCampaignWriteToRowValuesAutoGeneratedTextOptOutTest.class,
        BulkCampaignWriteToRowValuesImageOptOutPerformanceMaxSettingTest.class,
        BulkCampaignWriteToRowValuesPageFeedIdsPerformanceMaxSettingTest.class,
        BulkCampaignWriteToRowValuesTextOptOutPerformanceMaxSettingTest.class,
        BulkCampaignWriteToRowValuesCostPerSaleOptOutTest.class,
        BulkCampaignWriteToRowValuesAppIdTest.class,
        BulkCampaignWriteToRowValuesAppStoreTest.class,
        BulkCampaignWriteToRowValuesNewCustomerAcquisitionBidOnlyModeTest.class,
        BulkCampaignWriteToRowValuesNewCustomerAcquisitionGoalIdTest.class,
        BulkCampaignWriteToRowValuesAdditionalConversionValueTest.class,
        BulkCampaignWriteToRowValuesIsPoliticalTest.class
})
public class BulkCampaignWriteTests {

}
