package com.microsoft.bingads.v13.api.test.entities.campaign;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

import com.microsoft.bingads.v13.api.test.entities.campaign.read.*;

@RunWith(Suite.class)
@SuiteClasses({
        BulkCampaignReadFromRowValuesAccountIdTest.class,
        BulkCampaignReadFromRowValuesBudgetTypeTest.class,
        BulkCampaignReadFromRowValuesDailyBudgetTest.class,
        BulkCampaignReadFromRowValuesIdTest.class,
        BulkCampaignReadFromRowValuesKeywordRelevanceNotSetTest.class,
        BulkCampaignReadFromRowValuesKeywordRelevanceTest.class,
        BulkCampaignReadFromRowValuesLandingPageRelevanceNotSetTest.class,
        BulkCampaignReadFromRowValuesLandingPageRelevanceTest.class,
        BulkCampaignReadFromRowValuesLandingPageUserExperienceNotSetTest.class,
        BulkCampaignReadFromRowValuesLandingPageUserExperienceTest.class,
        BulkCampaignReadFromRowValuesNameTest.class,
        BulkCampaignReadFromRowValuesQualityScoreNotSetTest.class,
        BulkCampaignReadFromRowValuesQualityScoreTest.class,
        BulkCampaignReadFromRowValuesStatusTest.class,
        BulkCampaignReadFromRowValuesTimeZoneTest.class,
        BulkCampaignReadFromRowValuesAudienceAdsBidAdjustmentTest.class,
        BulkCampaignReadFromRowValuesCampaignTypeTest.class,
        BulkCampaignReadFromRowValuesSettingsTest.class,
        BulkCampaignReadFromRowValuesBidStrategyTypeTest.class,
        BulkCampaignReadFromRowValuesDisclaimerSettingsTest.class,
        BulkCampaignReadFromRowValuesDSASettingsTest.class,
        BulkCampaignReadFromRowValuesExperimentIdTest.class,
        BulkCampaignReadFromRowValuesFinalUrlSuffixTest.class,
        BulkCampaignReadAdScheduleUseSearcherTimeZone.class,
        BulkCampaignReadFromRowValuesBidStrategyIdTest.class,
        BulkCampaignReadFromRowValuesBidStrategyNameTest.class,
        BulkCampaignReadFromRowValuesDynamicFeedSettingsTest.class,
        BulkCampaignReadFromRowValuesMultiMediaAdBidAdjustmentTest.class,
        //BulkCampaignReadFromRowValuesVerifiedTrackingSettingsTest.class,
        BulkCampaignReadFromRowValuesPerformanceMaxSettingsTest.class,
        BulkCampaignReadFromRowValuesDestinationChannelTest.class,
        BulkCampaignReadFromRowValuesIsMultiChannelCampaignTest.class,
        BulkCampaignReadFromRowValuesAutoGeneratedImageOptOutTest.class,
        BulkCampaignReadFromRowValuesAutoGeneratedTextOptOutTest.class,
        BulkCampaignReadFromRowValuesAppSettingTest.class,
})
public class BulkCampaignReadTests {

}
