
package com.microsoft.bingads.adintelligence;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AdIntelligenceService", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", wsdlLocation = "https://api.sandbox.bingads.microsoft.com/Api/Advertiser/AdIntelligence/v9/AdIntelligenceService.svc?wsdl")
public class AdIntelligenceService
    extends Service
{

    private final static URL ADINTELLIGENCESERVICE_WSDL_LOCATION;
    private final static WebServiceException ADINTELLIGENCESERVICE_EXCEPTION;
    private final static QName ADINTELLIGENCESERVICE_QNAME = new QName("https://bingads.microsoft.com/AdIntelligence/v9", "AdIntelligenceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.sandbox.bingads.microsoft.com/Api/Advertiser/AdIntelligence/v9/AdIntelligenceService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADINTELLIGENCESERVICE_WSDL_LOCATION = url;
        ADINTELLIGENCESERVICE_EXCEPTION = e;
    }

    public AdIntelligenceService() {
        super(__getWsdlLocation(), ADINTELLIGENCESERVICE_QNAME);
    }

    public AdIntelligenceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns IAdIntelligenceService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAdIntelligenceService")
    public IAdIntelligenceService getBasicHttpBindingIAdIntelligenceService() {
        return super.getPort(new QName("https://bingads.microsoft.com/AdIntelligence/v9", "BasicHttpBinding_IAdIntelligenceService"), IAdIntelligenceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAdIntelligenceService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAdIntelligenceService")
    public IAdIntelligenceService getBasicHttpBindingIAdIntelligenceService(WebServiceFeature... features) {
        return super.getPort(new QName("https://bingads.microsoft.com/AdIntelligence/v9", "BasicHttpBinding_IAdIntelligenceService"), IAdIntelligenceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADINTELLIGENCESERVICE_EXCEPTION!= null) {
            throw ADINTELLIGENCESERVICE_EXCEPTION;
        }
        return ADINTELLIGENCESERVICE_WSDL_LOCATION;
    }

}
