
package com.microsoft.bingads.adintelligence;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IAdIntelligenceService", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAdIntelligenceService {


    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetPublisherKeywordPerformanceResponse>
     */
    @WebMethod(operationName = "GetPublisherKeywordPerformance", action = "GetPublisherKeywordPerformance")
    public Response<GetPublisherKeywordPerformanceResponse> getPublisherKeywordPerformanceAsync(
        @WebParam(name = "GetPublisherKeywordPerformanceRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetPublisherKeywordPerformanceRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetPublisherKeywordPerformance", action = "GetPublisherKeywordPerformance")
    public Future<?> getPublisherKeywordPerformanceAsync(
        @WebParam(name = "GetPublisherKeywordPerformanceRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetPublisherKeywordPerformanceRequest parameters,
        @WebParam(name = "GetPublisherKeywordPerformanceResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetPublisherKeywordPerformanceResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetPublisherKeywordPerformanceResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetPublisherKeywordPerformance", action = "GetPublisherKeywordPerformance")
    @WebResult(name = "GetPublisherKeywordPerformanceResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetPublisherKeywordPerformanceResponse getPublisherKeywordPerformance(
        @WebParam(name = "GetPublisherKeywordPerformanceRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetPublisherKeywordPerformanceRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.SuggestKeywordsForUrlResponse>
     */
    @WebMethod(operationName = "SuggestKeywordsForUrl", action = "SuggestKeywordsForUrl")
    public Response<SuggestKeywordsForUrlResponse> suggestKeywordsForUrlAsync(
        @WebParam(name = "SuggestKeywordsForUrlRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        SuggestKeywordsForUrlRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SuggestKeywordsForUrl", action = "SuggestKeywordsForUrl")
    public Future<?> suggestKeywordsForUrlAsync(
        @WebParam(name = "SuggestKeywordsForUrlRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        SuggestKeywordsForUrlRequest parameters,
        @WebParam(name = "SuggestKeywordsForUrlResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SuggestKeywordsForUrlResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.SuggestKeywordsForUrlResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "SuggestKeywordsForUrl", action = "SuggestKeywordsForUrl")
    @WebResult(name = "SuggestKeywordsForUrlResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public SuggestKeywordsForUrlResponse suggestKeywordsForUrl(
        @WebParam(name = "SuggestKeywordsForUrlRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        SuggestKeywordsForUrlRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetEstimatedBidByKeywordIdsResponse>
     */
    @WebMethod(operationName = "GetEstimatedBidByKeywordIds", action = "GetEstimatedBidByKeywordIds")
    public Response<GetEstimatedBidByKeywordIdsResponse> getEstimatedBidByKeywordIdsAsync(
        @WebParam(name = "GetEstimatedBidByKeywordIdsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetEstimatedBidByKeywordIdsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetEstimatedBidByKeywordIds", action = "GetEstimatedBidByKeywordIds")
    public Future<?> getEstimatedBidByKeywordIdsAsync(
        @WebParam(name = "GetEstimatedBidByKeywordIdsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetEstimatedBidByKeywordIdsRequest parameters,
        @WebParam(name = "GetEstimatedBidByKeywordIdsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetEstimatedBidByKeywordIdsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetEstimatedBidByKeywordIdsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetEstimatedBidByKeywordIds", action = "GetEstimatedBidByKeywordIds")
    @WebResult(name = "GetEstimatedBidByKeywordIdsResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetEstimatedBidByKeywordIdsResponse getEstimatedBidByKeywordIds(
        @WebParam(name = "GetEstimatedBidByKeywordIdsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetEstimatedBidByKeywordIdsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetEstimatedPositionByKeywordIdsResponse>
     */
    @WebMethod(operationName = "GetEstimatedPositionByKeywordIds", action = "GetEstimatedPositionByKeywordIds")
    public Response<GetEstimatedPositionByKeywordIdsResponse> getEstimatedPositionByKeywordIdsAsync(
        @WebParam(name = "GetEstimatedPositionByKeywordIdsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetEstimatedPositionByKeywordIdsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetEstimatedPositionByKeywordIds", action = "GetEstimatedPositionByKeywordIds")
    public Future<?> getEstimatedPositionByKeywordIdsAsync(
        @WebParam(name = "GetEstimatedPositionByKeywordIdsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetEstimatedPositionByKeywordIdsRequest parameters,
        @WebParam(name = "GetEstimatedPositionByKeywordIdsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetEstimatedPositionByKeywordIdsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetEstimatedPositionByKeywordIdsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetEstimatedPositionByKeywordIds", action = "GetEstimatedPositionByKeywordIds")
    @WebResult(name = "GetEstimatedPositionByKeywordIdsResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetEstimatedPositionByKeywordIdsResponse getEstimatedPositionByKeywordIds(
        @WebParam(name = "GetEstimatedPositionByKeywordIdsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetEstimatedPositionByKeywordIdsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetEstimatedBidByKeywordsResponse>
     */
    @WebMethod(operationName = "GetEstimatedBidByKeywords", action = "GetEstimatedBidByKeywords")
    public Response<GetEstimatedBidByKeywordsResponse> getEstimatedBidByKeywordsAsync(
        @WebParam(name = "GetEstimatedBidByKeywordsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetEstimatedBidByKeywordsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetEstimatedBidByKeywords", action = "GetEstimatedBidByKeywords")
    public Future<?> getEstimatedBidByKeywordsAsync(
        @WebParam(name = "GetEstimatedBidByKeywordsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetEstimatedBidByKeywordsRequest parameters,
        @WebParam(name = "GetEstimatedBidByKeywordsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetEstimatedBidByKeywordsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetEstimatedBidByKeywordsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetEstimatedBidByKeywords", action = "GetEstimatedBidByKeywords")
    @WebResult(name = "GetEstimatedBidByKeywordsResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetEstimatedBidByKeywordsResponse getEstimatedBidByKeywords(
        @WebParam(name = "GetEstimatedBidByKeywordsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetEstimatedBidByKeywordsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetEstimatedPositionByKeywordsResponse>
     */
    @WebMethod(operationName = "GetEstimatedPositionByKeywords", action = "GetEstimatedPositionByKeywords")
    public Response<GetEstimatedPositionByKeywordsResponse> getEstimatedPositionByKeywordsAsync(
        @WebParam(name = "GetEstimatedPositionByKeywordsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetEstimatedPositionByKeywordsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetEstimatedPositionByKeywords", action = "GetEstimatedPositionByKeywords")
    public Future<?> getEstimatedPositionByKeywordsAsync(
        @WebParam(name = "GetEstimatedPositionByKeywordsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetEstimatedPositionByKeywordsRequest parameters,
        @WebParam(name = "GetEstimatedPositionByKeywordsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetEstimatedPositionByKeywordsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetEstimatedPositionByKeywordsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetEstimatedPositionByKeywords", action = "GetEstimatedPositionByKeywords")
    @WebResult(name = "GetEstimatedPositionByKeywordsResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetEstimatedPositionByKeywordsResponse getEstimatedPositionByKeywords(
        @WebParam(name = "GetEstimatedPositionByKeywordsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetEstimatedPositionByKeywordsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetHistoricalSearchCountResponse>
     */
    @WebMethod(operationName = "GetHistoricalSearchCount", action = "GetHistoricalSearchCount")
    public Response<GetHistoricalSearchCountResponse> getHistoricalSearchCountAsync(
        @WebParam(name = "GetHistoricalSearchCountRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetHistoricalSearchCountRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetHistoricalSearchCount", action = "GetHistoricalSearchCount")
    public Future<?> getHistoricalSearchCountAsync(
        @WebParam(name = "GetHistoricalSearchCountRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetHistoricalSearchCountRequest parameters,
        @WebParam(name = "GetHistoricalSearchCountResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetHistoricalSearchCountResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetHistoricalSearchCountResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetHistoricalSearchCount", action = "GetHistoricalSearchCount")
    @WebResult(name = "GetHistoricalSearchCountResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetHistoricalSearchCountResponse getHistoricalSearchCount(
        @WebParam(name = "GetHistoricalSearchCountRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetHistoricalSearchCountRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetHistoricalKeywordPerformanceResponse>
     */
    @WebMethod(operationName = "GetHistoricalKeywordPerformance", action = "GetHistoricalKeywordPerformance")
    public Response<GetHistoricalKeywordPerformanceResponse> getHistoricalKeywordPerformanceAsync(
        @WebParam(name = "GetHistoricalKeywordPerformanceRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetHistoricalKeywordPerformanceRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetHistoricalKeywordPerformance", action = "GetHistoricalKeywordPerformance")
    public Future<?> getHistoricalKeywordPerformanceAsync(
        @WebParam(name = "GetHistoricalKeywordPerformanceRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetHistoricalKeywordPerformanceRequest parameters,
        @WebParam(name = "GetHistoricalKeywordPerformanceResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetHistoricalKeywordPerformanceResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetHistoricalKeywordPerformanceResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetHistoricalKeywordPerformance", action = "GetHistoricalKeywordPerformance")
    @WebResult(name = "GetHistoricalKeywordPerformanceResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetHistoricalKeywordPerformanceResponse getHistoricalKeywordPerformance(
        @WebParam(name = "GetHistoricalKeywordPerformanceRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetHistoricalKeywordPerformanceRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.SuggestKeywordsFromExistingKeywordsResponse>
     */
    @WebMethod(operationName = "SuggestKeywordsFromExistingKeywords", action = "SuggestKeywordsFromExistingKeywords")
    public Response<SuggestKeywordsFromExistingKeywordsResponse> suggestKeywordsFromExistingKeywordsAsync(
        @WebParam(name = "SuggestKeywordsFromExistingKeywordsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        SuggestKeywordsFromExistingKeywordsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "SuggestKeywordsFromExistingKeywords", action = "SuggestKeywordsFromExistingKeywords")
    public Future<?> suggestKeywordsFromExistingKeywordsAsync(
        @WebParam(name = "SuggestKeywordsFromExistingKeywordsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        SuggestKeywordsFromExistingKeywordsRequest parameters,
        @WebParam(name = "SuggestKeywordsFromExistingKeywordsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<SuggestKeywordsFromExistingKeywordsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.SuggestKeywordsFromExistingKeywordsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "SuggestKeywordsFromExistingKeywords", action = "SuggestKeywordsFromExistingKeywords")
    @WebResult(name = "SuggestKeywordsFromExistingKeywordsResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public SuggestKeywordsFromExistingKeywordsResponse suggestKeywordsFromExistingKeywords(
        @WebParam(name = "SuggestKeywordsFromExistingKeywordsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        SuggestKeywordsFromExistingKeywordsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetKeywordLocationsResponse>
     */
    @WebMethod(operationName = "GetKeywordLocations", action = "GetKeywordLocations")
    public Response<GetKeywordLocationsResponse> getKeywordLocationsAsync(
        @WebParam(name = "GetKeywordLocationsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetKeywordLocationsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetKeywordLocations", action = "GetKeywordLocations")
    public Future<?> getKeywordLocationsAsync(
        @WebParam(name = "GetKeywordLocationsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetKeywordLocationsRequest parameters,
        @WebParam(name = "GetKeywordLocationsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetKeywordLocationsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetKeywordLocationsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetKeywordLocations", action = "GetKeywordLocations")
    @WebResult(name = "GetKeywordLocationsResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetKeywordLocationsResponse getKeywordLocations(
        @WebParam(name = "GetKeywordLocationsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetKeywordLocationsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetKeywordCategoriesResponse>
     */
    @WebMethod(operationName = "GetKeywordCategories", action = "GetKeywordCategories")
    public Response<GetKeywordCategoriesResponse> getKeywordCategoriesAsync(
        @WebParam(name = "GetKeywordCategoriesRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetKeywordCategoriesRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetKeywordCategories", action = "GetKeywordCategories")
    public Future<?> getKeywordCategoriesAsync(
        @WebParam(name = "GetKeywordCategoriesRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetKeywordCategoriesRequest parameters,
        @WebParam(name = "GetKeywordCategoriesResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetKeywordCategoriesResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetKeywordCategoriesResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetKeywordCategories", action = "GetKeywordCategories")
    @WebResult(name = "GetKeywordCategoriesResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetKeywordCategoriesResponse getKeywordCategories(
        @WebParam(name = "GetKeywordCategoriesRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetKeywordCategoriesRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetKeywordDemographicsResponse>
     */
    @WebMethod(operationName = "GetKeywordDemographics", action = "GetKeywordDemographics")
    public Response<GetKeywordDemographicsResponse> getKeywordDemographicsAsync(
        @WebParam(name = "GetKeywordDemographicsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetKeywordDemographicsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetKeywordDemographics", action = "GetKeywordDemographics")
    public Future<?> getKeywordDemographicsAsync(
        @WebParam(name = "GetKeywordDemographicsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetKeywordDemographicsRequest parameters,
        @WebParam(name = "GetKeywordDemographicsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetKeywordDemographicsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetKeywordDemographicsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetKeywordDemographics", action = "GetKeywordDemographics")
    @WebResult(name = "GetKeywordDemographicsResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetKeywordDemographicsResponse getKeywordDemographics(
        @WebParam(name = "GetKeywordDemographicsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetKeywordDemographicsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetBidLandscapeByKeywordIdsResponse>
     */
    @WebMethod(operationName = "GetBidLandscapeByKeywordIds", action = "GetBidLandscapeByKeywordIds")
    public Response<GetBidLandscapeByKeywordIdsResponse> getBidLandscapeByKeywordIdsAsync(
        @WebParam(name = "GetBidLandscapeByKeywordIdsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetBidLandscapeByKeywordIdsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetBidLandscapeByKeywordIds", action = "GetBidLandscapeByKeywordIds")
    public Future<?> getBidLandscapeByKeywordIdsAsync(
        @WebParam(name = "GetBidLandscapeByKeywordIdsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetBidLandscapeByKeywordIdsRequest parameters,
        @WebParam(name = "GetBidLandscapeByKeywordIdsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetBidLandscapeByKeywordIdsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetBidLandscapeByKeywordIdsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetBidLandscapeByKeywordIds", action = "GetBidLandscapeByKeywordIds")
    @WebResult(name = "GetBidLandscapeByKeywordIdsResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetBidLandscapeByKeywordIdsResponse getBidLandscapeByKeywordIds(
        @WebParam(name = "GetBidLandscapeByKeywordIdsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetBidLandscapeByKeywordIdsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetBidLandscapeByAdGroupIdsResponse>
     */
    @WebMethod(operationName = "GetBidLandscapeByAdGroupIds", action = "GetBidLandscapeByAdGroupIds")
    public Response<GetBidLandscapeByAdGroupIdsResponse> getBidLandscapeByAdGroupIdsAsync(
        @WebParam(name = "GetBidLandscapeByAdGroupIdsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetBidLandscapeByAdGroupIdsRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetBidLandscapeByAdGroupIds", action = "GetBidLandscapeByAdGroupIds")
    public Future<?> getBidLandscapeByAdGroupIdsAsync(
        @WebParam(name = "GetBidLandscapeByAdGroupIdsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetBidLandscapeByAdGroupIdsRequest parameters,
        @WebParam(name = "GetBidLandscapeByAdGroupIdsResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetBidLandscapeByAdGroupIdsResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetBidLandscapeByAdGroupIdsResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetBidLandscapeByAdGroupIds", action = "GetBidLandscapeByAdGroupIds")
    @WebResult(name = "GetBidLandscapeByAdGroupIdsResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetBidLandscapeByAdGroupIdsResponse getBidLandscapeByAdGroupIds(
        @WebParam(name = "GetBidLandscapeByAdGroupIdsRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetBidLandscapeByAdGroupIdsRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetAccountAuctionInsightResponse>
     */
    @WebMethod(operationName = "GetAccountAuctionInsight", action = "GetAccountAuctionInsight")
    public Response<GetAccountAuctionInsightResponse> getAccountAuctionInsightAsync(
        @WebParam(name = "GetAccountAuctionInsightRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetAccountAuctionInsightRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAccountAuctionInsight", action = "GetAccountAuctionInsight")
    public Future<?> getAccountAuctionInsightAsync(
        @WebParam(name = "GetAccountAuctionInsightRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetAccountAuctionInsightRequest parameters,
        @WebParam(name = "GetAccountAuctionInsightResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAccountAuctionInsightResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetAccountAuctionInsightResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetAccountAuctionInsight", action = "GetAccountAuctionInsight")
    @WebResult(name = "GetAccountAuctionInsightResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetAccountAuctionInsightResponse getAccountAuctionInsight(
        @WebParam(name = "GetAccountAuctionInsightRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetAccountAuctionInsightRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetCampaignAuctionInsightResponse>
     */
    @WebMethod(operationName = "GetCampaignAuctionInsight", action = "GetCampaignAuctionInsight")
    public Response<GetCampaignAuctionInsightResponse> getCampaignAuctionInsightAsync(
        @WebParam(name = "GetCampaignAuctionInsightRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetCampaignAuctionInsightRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetCampaignAuctionInsight", action = "GetCampaignAuctionInsight")
    public Future<?> getCampaignAuctionInsightAsync(
        @WebParam(name = "GetCampaignAuctionInsightRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetCampaignAuctionInsightRequest parameters,
        @WebParam(name = "GetCampaignAuctionInsightResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetCampaignAuctionInsightResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetCampaignAuctionInsightResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetCampaignAuctionInsight", action = "GetCampaignAuctionInsight")
    @WebResult(name = "GetCampaignAuctionInsightResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetCampaignAuctionInsightResponse getCampaignAuctionInsight(
        @WebParam(name = "GetCampaignAuctionInsightRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetCampaignAuctionInsightRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetAdGroupAuctionInsightResponse>
     */
    @WebMethod(operationName = "GetAdGroupAuctionInsight", action = "GetAdGroupAuctionInsight")
    public Response<GetAdGroupAuctionInsightResponse> getAdGroupAuctionInsightAsync(
        @WebParam(name = "GetAdGroupAuctionInsightRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetAdGroupAuctionInsightRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAdGroupAuctionInsight", action = "GetAdGroupAuctionInsight")
    public Future<?> getAdGroupAuctionInsightAsync(
        @WebParam(name = "GetAdGroupAuctionInsightRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetAdGroupAuctionInsightRequest parameters,
        @WebParam(name = "GetAdGroupAuctionInsightResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAdGroupAuctionInsightResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetAdGroupAuctionInsightResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetAdGroupAuctionInsight", action = "GetAdGroupAuctionInsight")
    @WebResult(name = "GetAdGroupAuctionInsightResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetAdGroupAuctionInsightResponse getAdGroupAuctionInsight(
        @WebParam(name = "GetAdGroupAuctionInsightRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetAdGroupAuctionInsightRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetKeywordAuctionInsightResponse>
     */
    @WebMethod(operationName = "GetKeywordAuctionInsight", action = "GetKeywordAuctionInsight")
    public Response<GetKeywordAuctionInsightResponse> getKeywordAuctionInsightAsync(
        @WebParam(name = "GetKeywordAuctionInsightRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetKeywordAuctionInsightRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetKeywordAuctionInsight", action = "GetKeywordAuctionInsight")
    public Future<?> getKeywordAuctionInsightAsync(
        @WebParam(name = "GetKeywordAuctionInsightRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetKeywordAuctionInsightRequest parameters,
        @WebParam(name = "GetKeywordAuctionInsightResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetKeywordAuctionInsightResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetKeywordAuctionInsightResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetKeywordAuctionInsight", action = "GetKeywordAuctionInsight")
    @WebResult(name = "GetKeywordAuctionInsightResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetKeywordAuctionInsightResponse getKeywordAuctionInsight(
        @WebParam(name = "GetKeywordAuctionInsightRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetKeywordAuctionInsightRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetAuctionInsightDataResponse>
     */
    @WebMethod(operationName = "GetAuctionInsightData", action = "GetAuctionInsightData")
    public Response<GetAuctionInsightDataResponse> getAuctionInsightDataAsync(
        @WebParam(name = "GetAuctionInsightDataRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetAuctionInsightDataRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAuctionInsightData", action = "GetAuctionInsightData")
    public Future<?> getAuctionInsightDataAsync(
        @WebParam(name = "GetAuctionInsightDataRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetAuctionInsightDataRequest parameters,
        @WebParam(name = "GetAuctionInsightDataResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAuctionInsightDataResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetAuctionInsightDataResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetAuctionInsightData", action = "GetAuctionInsightData")
    @WebResult(name = "GetAuctionInsightDataResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetAuctionInsightDataResponse getAuctionInsightData(
        @WebParam(name = "GetAuctionInsightDataRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetAuctionInsightDataRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetAuctionInsightAvailResponse>
     */
    @WebMethod(operationName = "GetAuctionInsightAvail", action = "GetAuctionInsightAvail")
    public Response<GetAuctionInsightAvailResponse> getAuctionInsightAvailAsync(
        @WebParam(name = "GetAuctionInsightAvailRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetAuctionInsightAvailRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAuctionInsightAvail", action = "GetAuctionInsightAvail")
    public Future<?> getAuctionInsightAvailAsync(
        @WebParam(name = "GetAuctionInsightAvailRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetAuctionInsightAvailRequest parameters,
        @WebParam(name = "GetAuctionInsightAvailResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAuctionInsightAvailResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetAuctionInsightAvailResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetAuctionInsightAvail", action = "GetAuctionInsightAvail")
    @WebResult(name = "GetAuctionInsightAvailResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetAuctionInsightAvailResponse getAuctionInsightAvail(
        @WebParam(name = "GetAuctionInsightAvailRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetAuctionInsightAvailRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetAuctionInsightAvailableChildrenResponse>
     */
    @WebMethod(operationName = "GetAuctionInsightAvailableChildren", action = "GetAuctionInsightAvailableChildren")
    public Response<GetAuctionInsightAvailableChildrenResponse> getAuctionInsightAvailableChildrenAsync(
        @WebParam(name = "GetAuctionInsightAvailableChildrenRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetAuctionInsightAvailableChildrenRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetAuctionInsightAvailableChildren", action = "GetAuctionInsightAvailableChildren")
    public Future<?> getAuctionInsightAvailableChildrenAsync(
        @WebParam(name = "GetAuctionInsightAvailableChildrenRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetAuctionInsightAvailableChildrenRequest parameters,
        @WebParam(name = "GetAuctionInsightAvailableChildrenResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetAuctionInsightAvailableChildrenResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetAuctionInsightAvailableChildrenResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetAuctionInsightAvailableChildren", action = "GetAuctionInsightAvailableChildren")
    @WebResult(name = "GetAuctionInsightAvailableChildrenResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetAuctionInsightAvailableChildrenResponse getAuctionInsightAvailableChildren(
        @WebParam(name = "GetAuctionInsightAvailableChildrenRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetAuctionInsightAvailableChildrenRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.ws.Response<com.microsoft.bingads.adintelligence.GetKeywordIdBidEstimationResponse>
     */
    @WebMethod(operationName = "GetKeywordIdBidEstimation", action = "GetKeywordIdBidEstimation")
    public Response<GetKeywordIdBidEstimationResponse> getKeywordIdBidEstimationAsync(
        @WebParam(name = "GetKeywordIdBidEstimationRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetKeywordIdBidEstimationRequest parameters);

    /**
     * 
     * @param asyncHandler
     * @param parameters
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "GetKeywordIdBidEstimation", action = "GetKeywordIdBidEstimation")
    public Future<?> getKeywordIdBidEstimationAsync(
        @WebParam(name = "GetKeywordIdBidEstimationRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetKeywordIdBidEstimationRequest parameters,
        @WebParam(name = "GetKeywordIdBidEstimationResponse", targetNamespace = "", partName = "asyncHandler")
        AsyncHandler<GetKeywordIdBidEstimationResponse> asyncHandler);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.microsoft.bingads.adintelligence.GetKeywordIdBidEstimationResponse
     * @throws ApiFaultDetail_Exception
     * @throws AdApiFaultDetail_Exception
     */
    @WebMethod(operationName = "GetKeywordIdBidEstimation", action = "GetKeywordIdBidEstimation")
    @WebResult(name = "GetKeywordIdBidEstimationResponse", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
    public GetKeywordIdBidEstimationResponse getKeywordIdBidEstimation(
        @WebParam(name = "GetKeywordIdBidEstimationRequest", targetNamespace = "https://bingads.microsoft.com/AdIntelligence/v9", partName = "parameters")
        GetKeywordIdBidEstimationRequest parameters)
        throws AdApiFaultDetail_Exception, ApiFaultDetail_Exception
    ;

}
