package com.microsoft.bingads.v13.api.test.restfulapi;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.junit.BeforeClass;
import org.junit.Test;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.microsoft.bingads.internal.restful.adaptor.AdaptorUtil;
import com.microsoft.bingads.v13.campaignmanagement.CampaignFrequencyCapSetting;
import com.microsoft.bingads.v13.campaignmanagement.Campaign;
import com.microsoft.bingads.v13.campaignmanagement.ChannelPlacementCriterion;
import com.microsoft.bingads.v13.campaignmanagement.Criterion;
import com.microsoft.bingads.v13.campaignmanagement.ImpressionTrackingSetting;
import com.microsoft.bingads.v13.campaignmanagement.ReachOptimizationGoal;
import com.microsoft.bingads.v13.campaignmanagement.ReachOptimizationGoalSetting;
import com.microsoft.bingads.v13.campaignmanagement.Setting;
import com.microsoft.bingads.v13.campaignmanagement.UnifiedAutomationSetting;

public class CampaignManagementRestParityTest {
    private static final ObjectMapper mapper = AdaptorUtil.mapper;

    @BeforeClass
    public static void registerRestAdapters() {
        com.microsoft.bingads.internal.restful.adaptor.generated.campaignmanagement.arrayOfTypes
                .AddMixInForArrayOfTypes.AddMixInForArrayOfTypes();
        com.microsoft.bingads.internal.restful.adaptor.generated.campaignmanagement.enums
                .AddMixInForEnumTypes.AddMixInForEnumTypes();
        com.microsoft.bingads.internal.restful.adaptor.generated.campaignmanagement.polymorphicTypes
                .AddMixInForPolymorphicTypes.AddMixInForPolymorphicTypes();
    }

    @Test
    public void impressionTrackingSettingRoundTripsThroughBaseSetting() throws Exception {
        Setting setting = roundTripSetting(
                "{\"Type\":\"ImpressionTrackingSetting\",\"ImpressionTrackingUrl\":\"https://example.com/track\"}",
                ImpressionTrackingSetting.class);
        assertEquals("https://example.com/track",
                ((ImpressionTrackingSetting) setting).getImpressionTrackingUrl());
    }

    @Test
    public void reachOptimizationGoalUsesApiEnumValues() throws Exception {
        Setting setting = roundTripSetting(
                "{\"Type\":\"ReachOptimizationGoalSetting\",\"OptimizationGoal\":\"MaxUniqueReach\"}",
                ReachOptimizationGoalSetting.class);
        assertEquals(ReachOptimizationGoal.MAX_UNIQUE_REACH,
                ((ReachOptimizationGoalSetting) setting).getOptimizationGoal());
        assertEquals("\"MaxImpressions\"",
                mapper.writeValueAsString(ReachOptimizationGoal.MAX_IMPRESSIONS));
        assertEquals(ReachOptimizationGoal.MAX_IMPRESSIONS,
                mapper.readValue("\"MaxImpressions\"", ReachOptimizationGoal.class));
    }

    @Test
    public void campaignSettingsPreservePolymorphicRestValues() throws Exception {
        String json = "{\"Settings\":[{\"Type\":\"ReachOptimizationGoalSetting\","
                + "\"OptimizationGoal\":\"MaxUniqueReach\"}]}";
        Campaign campaign = mapper.readValue(json, Campaign.class);
        assertTrue(campaign.getSettings().getSettings().get(0) instanceof ReachOptimizationGoalSetting);
        assertEquals(mapper.readTree(json), mapper.readTree(mapper.writeValueAsString(campaign)));
    }

    @Test
    public void campaignFrequencyCapSettingRoundTripsThroughBaseSetting() throws Exception {
        Setting setting = roundTripSetting(
                "{\"Type\":\"CampaignFrequencyCapSetting\",\"CapValue\":5,\"TimeGranularity\":\"DAY\"}",
                CampaignFrequencyCapSetting.class);
        assertEquals(Integer.valueOf(5), ((CampaignFrequencyCapSetting) setting).getCapValue());
    }

    @Test
    public void unifiedAutomationSettingRoundTripsThroughBaseSetting() throws Exception {
        Setting setting = roundTripSetting(
                "{\"Type\":\"UnifiedAutomationSetting\",\"AutoGeneratedTextOptOut\":true}",
                UnifiedAutomationSetting.class);
        assertEquals(Boolean.TRUE, ((UnifiedAutomationSetting) setting).getAutoGeneratedTextOptOut());
    }

    @Test
    public void channelPlacementCriterionRoundTripsThroughBaseCriterion() throws Exception {
        String json = "{\"Type\":\"ChannelPlacementCriterion\",\"ChannelId\":10,"
                + "\"ChannelPlacementId\":\"42\",\"SubChannelName\":\"Subchannel\"}";
        Criterion criterion = mapper.readValue(json, Criterion.class);
        assertTrue(criterion instanceof ChannelPlacementCriterion);
        assertEquals(Integer.valueOf(10), ((ChannelPlacementCriterion) criterion).getChannelId());
        assertEquals(Long.valueOf(42), ((ChannelPlacementCriterion) criterion).getChannelPlacementId());
        assertEquals(mapper.readTree(json), mapper.readTree(mapper.writeValueAsString(criterion)));
    }

    private Setting roundTripSetting(String json, Class<? extends Setting> expectedType) throws Exception {
        Setting setting = mapper.readValue(json, Setting.class);
        assertTrue(expectedType.isInstance(setting));
        assertEquals(mapper.readTree(json), mapper.readTree(mapper.writeValueAsString(setting)));
        return setting;
    }
}
