
package com.microsoft.bingads.v13.bulk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BulkService", targetNamespace = "https://bingads.microsoft.com/CampaignManagement/v13", wsdlLocation = "https://bulk.api.sandbox.bingads.microsoft.com/Api/Advertiser/CampaignManagement/v13/BulkService.svc?wsdl")
public class BulkService
    extends Service
{

    private static final URL BULKSERVICE_WSDL_LOCATION;
    private static final WebServiceException BULKSERVICE_EXCEPTION;
    private static final QName BULKSERVICE_QNAME = new QName("https://bingads.microsoft.com/CampaignManagement/v13", "BulkService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://bulk.api.sandbox.bingads.microsoft.com/Api/Advertiser/CampaignManagement/v13/BulkService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BULKSERVICE_WSDL_LOCATION = url;
        BULKSERVICE_EXCEPTION = e;
    }

    public BulkService() {
        super(__getWsdlLocation(), BULKSERVICE_QNAME);
    }

    public BulkService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BULKSERVICE_QNAME, features);
    }

    public BulkService(URL wsdlLocation) {
        super(wsdlLocation, BULKSERVICE_QNAME);
    }

    public BulkService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BULKSERVICE_QNAME, features);
    }

    public BulkService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BulkService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IBulkService
     */
    @WebEndpoint(name = "BasicHttpBinding_IBulkService")
    public IBulkService getBasicHttpBindingIBulkService() {
        return super.getPort(new QName("https://bingads.microsoft.com/CampaignManagement/v13", "BasicHttpBinding_IBulkService"), IBulkService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBulkService
     */
    @WebEndpoint(name = "BasicHttpBinding_IBulkService")
    public IBulkService getBasicHttpBindingIBulkService(WebServiceFeature... features) {
        return super.getPort(new QName("https://bingads.microsoft.com/CampaignManagement/v13", "BasicHttpBinding_IBulkService"), IBulkService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BULKSERVICE_EXCEPTION!= null) {
            throw BULKSERVICE_EXCEPTION;
        }
        return BULKSERVICE_WSDL_LOCATION;
    }

}
